"""
Auto-generated member bios — regenerate with generate_bios.py
"""

MEMBER_BIOS = {
    "A000055": "Robert B. Aderholt is a member of the United States House of Representatives from AL.",
    "A000148": "Jake Auchincloss is a member of the United States House of Representatives from MA.",
    "A000369": "Mark E. Amodei is a member of the United States House of Representatives from NV.",
    "A000370": "Alma S. Adams is a member of the United States House of Representatives from NC.",
    "A000371": "Pete Aguilar is a member of the United States House of Representatives from CA.",
    "A000372": "Rick W. Allen is a member of the United States House of Representatives from GA.",
    "A000375": "Jodey Cook Arrington is an American politician serving as the U.S. representative for Texas's 19th congressional district since 2017. The district includes a large slice of West Texas, centered around Lubbock and Abilene. He is a member of the Republican Party.",
    "A000379": "Mark Alford is a member of the United States House of Representatives from MO.",
    "A000380": "Gabe Amo is a member of the United States House of Representatives from RI.",
    "A000381": "Yassamin Ansari is a member of the United States House of Representatives from AZ.",
    "A000382": "Angela D. Alsobrooks is a member of the United States Senate from MD.",
    "A000383": "Alan Armstrong is a member of the United States Senate from OK.",
    "B000490": "Sanford D. Bishop, Jr. is a member of the United States House of Representatives from GA.",
    "B000668": "Cliff Stewart Bentz (born January 12, 1952) is an American politician and lawyer serving as the U.S. representative for Oregon's 2nd congressional district since 2021. He previously served in the Oregon Senate from 2018 to 2020 and in the Oregon House of Representatives from 2008 to 2018. He is a member of the Republican Party.",
    "B000740": "Stephanie I. Bice is a member of the United States House of Representatives from OK.",
    "B000825": "Lauren Boebert is a member of the United States House of Representatives from CO.",
    "B001230": "Tammy Baldwin is a member of the United States Senate from WI.",
    "B001236": "John Nichols Boozman is an American politician and former optometrist serving as the senior United States senator from Arkansas, a seat he has held since 2011. From 2001 to 2011, he served as the U.S. representative for Arkansas's 3rd congressional district. A member of the Republican Party, Boozman has been the dean of Arkansas's congressional delegation since 2013.",
    "B001243": "Marsha Blackburn is a member of the United States Senate from TN.",
    "B001257": "Gus M. Bilirakis is a member of the United States House of Representatives from FL.",
    "B001260": "Vern Buchanan is a member of the United States House of Representatives from FL.",
    "B001261": "John Anthony Barrasso III ( bə-RAH-soh; born July 21, 1952) is an American physician and politician serving as the senior United States senator from Wyoming, a seat he has held since 2007. A member of the Republican Party, he served in the Wyoming State Senate from 2003 to 2007. In 2025, he became Senate majority whip, the second-ranking Senate Republican. Born and raised in Reading, Pennsylvania, Barrasso graduated from Georgetown University, where he received his B.S.",
    "B001267": "Michael F. Bennet is a member of the United States Senate from CO.",
    "B001277": "Richard Blumenthal is a member of the United States Senate from CT.",
    "B001278": "Suzanne Bonamici is a member of the United States House of Representatives from OR.",
    "B001281": "Joyce Beatty is a member of the United States House of Representatives from OH.",
    "B001282": "Andy Barr is a member of the United States House of Representatives from KY.",
    "B001285": "Julia Brownley is a member of the United States House of Representatives from CA.",
    "B001287": "Ami Bera is a member of the United States House of Representatives from CA.",
    "B001288": "Cory A. Booker is a member of the United States Senate from NJ.",
    "B001291": "Brian Babin is a member of the United States House of Representatives from TX.",
    "B001292": "Donald S. Beyer, Jr. is a member of the United States House of Representatives from VA.",
    "B001295": "Michael Joseph Bost ( BAWST; born December 30, 1960) is an American politician serving as the U.S. representative for Illinois's 12th congressional district since 2015. Previously, Bost was a member of the Illinois House of Representatives, representing the 115th district from 1995 to 2015. Before entering politics, he was a firefighter.",
    "B001296": "Brendan F. Boyle is a member of the United States House of Representatives from PA.",
    "B001298": "Don Bacon is a member of the United States House of Representatives from NE.",
    "B001299": "Jim Banks is a member of the United States Senate from IN.",
    "B001300": "Nanette Diaz Barragán is a member of the United States House of Representatives from CA.",
    "B001301": "Jack Bergman is a member of the United States House of Representatives from MI.",
    "B001302": "Andy Biggs is a member of the United States House of Representatives from AZ.",
    "B001303": "Lisa Blunt Rochester is a member of the United States Senate from DE.",
    "B001305": "Ted Budd is a member of the United States Senate from NC.",
    "B001306": "Troy Balderson is a member of the United States House of Representatives from OH.",
    "B001307": "James Baird may refer to: Sir James Baird, 2nd Baronet (c. 1658–1715), British baronet James Baird (British Army officer) (1915–2007) James Baird (civil engineer) (1872–1953), builder of the Lincoln Memorial and quarterback of the Michigan Wolverines football team James Baird (footballer) (born 1983), Scottish goalkeeper/soccer player James Baird (industrialist) (1802–1876), Scottish industrialist and MP for Falkirk Burghs James Baird (merchant) (1828–1915), Newfoundland merchant and activist James Baird (trade unionist) (1878–1948), Northern Irish politician and activist James Bryson Baird (1859–1939), Canadian politician Jim Baird (American football) (1874–1938), American college football player of the 1890s Jim Baird (Australian footballer) (1920–2003), Australian rules footballer Jim Baird (politician) (born 1945), U.S. representative from Indiana Jim Baird (rugby union), New Zealand international rugby union player See also James Baird State Park in New York",
    "B001309": "Tim Burchett is a member of the United States House of Representatives from TN.",
    "B001313": "Shontel M. Brown is a member of the United States House of Representatives from OH.",
    "B001314": "Aaron Bean is a member of the United States House of Representatives from FL.",
    "B001315": "Nikki Budzinski is a member of the United States House of Representatives from IL.",
    "B001316": "Eric Burlison is a member of the United States House of Representatives from MO.",
    "B001317": "Joshua Chad Brecheen (, brə-KEEN, born June 19, 1979) is a Native American politician who has served as the U.S. representative for Oklahoma's 2nd congressional district since 2023. A member of the Republican Party, he previously served in the Oklahoma Senate from 2010 to 2018. He is a citizen of the Choctaw Nation.",
    "B001318": "Becca Balint is a member of the United States House of Representatives from VT.",
    "B001319": "Katie Boyd Britt is a member of the United States Senate from AL.",
    "B001321": "Tom Barrett is a member of the United States House of Representatives from MI.",
    "B001322": "Michael Baumgartner is a member of the United States House of Representatives from WA.",
    "B001323": "Nicholas J. Begich III is a member of the United States House of Representatives from AK.",
    "B001324": "Wesley Bell is a member of the United States House of Representatives from MO.",
    "B001325": "Sheryl Lynn Biggs (born March 28, 1970) is an American politician from South Carolina. A Republican, she represents South Carolina's 3rd congressional district in the United States House of Representatives. Early life Biggs is from Kosciusko, Mississippi. She graduated from Kosciusko High School in 1988, from Carolina Bible College with a bachelor's degree in Christian ministries, and from Samford University with a Doctor of Nursing Practice.",
    "B001326": "Janelle S. Bynum is a member of the United States House of Representatives from OR.",
    "B001327": "Robert P. Bresnahan, Jr. is a member of the United States House of Representatives from PA.",
    "C000059": "Ken Calvert is a member of the United States House of Representatives from CA.",
    "C000127": "Maria Ellen Cantwell (; born October 13, 1958) is an American politician serving since 2001 as the junior U.S. A member of the Democratic Party, she served from 1987 to 1993 in the Washington House of Representatives and from 1993 to 1995 in the United States House of Representatives. Born and raised in Indianapolis, Indiana, Cantwell graduated from Miami University before moving to Seattle to work on Alan Cranston's 1984 presidential campaign. In 1986, she was elected to the state house of representatives, where she served until her election to Congress in 1992.",
    "C000537": "James E. Clyburn is a member of the United States House of Representatives from SC.",
    "C000880": "Michael Dean Crapo is an American lawyer and politician serving as the senior United States senator from Idaho, a seat he has held since 1999. A member of the Republican Party, Crapo served from 1993 to 1999 as the U.S. representative for Idaho's 2nd congressional district.",
    "C001035": "Susan Margaret Collins (born December 7, 1952) is an American politician serving as the senior United States senator for Maine since 1997. A member of the Republican Party, she is Maine's longest-serving member of Congress and the longest-serving Republican woman in the Senate. Collins has chaired the Senate Appropriations Committee since 2025. Born in Caribou, Maine, Collins is a graduate of St.",
    "C001039": "Kat Cammack is a member of the United States House of Representatives from FL.",
    "C001047": "Shelley Wellons Moore Capito is an American politician serving as the senior United States senator from West Virginia. A member of the Republican Party, Capito served from 2001 to 2015 as the U.S. representative from West Virginia's 2nd congressional district. She is the daughter of three-term West Virginia governor and six-term U.S.",
    "C001051": "John R. Carter is a member of the United States House of Representatives from TX.",
    "C001053": "Tom Cole is a member of the United States House of Representatives from OK.",
    "C001055": "Ed Case is a member of the United States House of Representatives from HI.",
    "C001056": "John Cornyn is a member of the United States Senate from TX.",
    "C001059": "Jim Costa is a member of the United States House of Representatives from CA.",
    "C001061": "Emanuel Cleaver is a member of the United States House of Representatives from MO.",
    "C001063": "Enrique Roberto \"Henry\" Cuellar ( KWAY-ar; born September 19, 1955) is an American politician and attorney serving as the U.S. representative for Texas's 28th congressional district since 2005. He is a member of the Democratic Party, and his district spans from the Rio Grande toward the suburbs of San Antonio. Cuellar served in the Texas House of Representatives for 14 years, from 1987 to 2001, and briefly served as the Texas secretary of state in 2001, making him, as of 2025, the most recent Democrat to have held a statewide office in Texas.",
    "C001066": "Kathy Castor is a member of the United States House of Representatives from FL.",
    "C001067": "Yvette D. Clarke is a member of the United States House of Representatives from NY.",
    "C001068": "Steve Cohen is a member of the United States House of Representatives from TN.",
    "C001069": "Joe Courtney is a member of the United States House of Representatives from CT.",
    "C001072": "André Carson is a member of the United States House of Representatives from IN.",
    "C001075": "Bill Cassidy is a member of the United States Senate from LA.",
    "C001080": "Judy Chu is a member of the United States House of Representatives from CA.",
    "C001087": "Eric Crawford may refer to:Eric Crawford (soccer) for Toronto Lynx\nEric Crawford (Taken)\nEric Crawford on WDRB\nEric Crawford, co-writer of I Can't Hear the Music\nRick Crawford (politician), Member of the U.S. House of Representatives from Arkansas",
    "C001088": "Christopher A. Coons is a member of the United States Senate from DE.",
    "C001091": "Joaquin Castro is a member of the United States House of Representatives from TX.",
    "C001095": "Tom Cotton is a member of the United States Senate from AR.",
    "C001096": "Kevin Cramer is a member of the United States Senate from ND.",
    "C001098": "Ted Cruz is a member of the United States Senate from TX.",
    "C001101": "Katherine M. Clark is a member of the United States House of Representatives from MA.",
    "C001103": "Earl L. \"Buddy\" Carter is a member of the United States House of Representatives from GA.",
    "C001108": "James Comer is a member of the United States House of Representatives from KY.",
    "C001110": "J. Luis Correa is a member of the United States House of Representatives from CA.",
    "C001112": "Salud O. Carbajal is a member of the United States House of Representatives from CA.",
    "C001113": "Catherine Cortez Masto is a member of the United States Senate from NV.",
    "C001114": "John R. Curtis is a member of the United States Senate from UT.",
    "C001115": "Michael Cloud is a member of the United States House of Representatives from TX.",
    "C001116": "Andrew S. Clyde is a member of the United States House of Representatives from GA.",
    "C001117": "Sean Thomas Casten (born November 23, 1971) is an American businessman and politician serving as the U.S. representative for Illinois's 6th congressional district. The district covers southwestern Chicago, as well as many of Chicago's inner southwestern suburbs, such as Downers Grove, Wheaton, Lisle, Orland Park, and Western Springs. He is a member of the Democratic Party.",
    "C001118": "Ben Cline is a member of the United States House of Representatives from VA.",
    "C001119": "Angie Craig is a member of the United States House of Representatives from MN.",
    "C001120": "Dan Crenshaw is a member of the United States House of Representatives from TX.",
    "C001121": "Jason Crow is a member of the United States House of Representatives from CO.",
    "C001123": "Gilbert Ray Cisneros, Jr. is a member of the United States House of Representatives from CA.",
    "C001125": "Troy A. Carter is a member of the United States House of Representatives from LA.",
    "C001126": "Mike Carey is a member of the United States House of Representatives from OH.",
    "C001129": "Mike Collins is a member of the United States House of Representatives from GA.",
    "C001130": "Jasmine Crockett is a member of the United States House of Representatives from TX.",
    "C001131": "Greg Casar is a member of the United States House of Representatives from TX.",
    "C001132": "Elijah Crane is a member of the United States House of Representatives from AZ.",
    "C001133": "Juan Ciscomani is a member of the United States House of Representatives from AZ.",
    "C001136": "Herbert C. Conaway, Jr. is a member of the United States House of Representatives from NJ.",
    "C001137": "Jeff Crank is a member of the United States House of Representatives from CO.",
    "D000032": "Byron Donalds is a member of the United States House of Representatives from FL.",
    "D000096": "Davis is an American politician serving as the U.S. representative for Illinois's 7th congressional district since 1997. The district includes much of western Chicago, as well as the Loop. It also encompasses several of Chicago's inner western suburbs, such as Bellwood, Oak Park, and River Forest.",
    "D000197": "Diana Louise DeGette ( dih-GHET; born July 29, 1957) is an American lawyer and politician serving as the U.S. representative for Colorado's 1st congressional district since 1997. A member of the Democratic Party, her district is based in Denver. DeGette was a chief deputy whip from 2005 to 2019 and is the dean of Colorado's congressional delegation since 2007; she served as the state representative for the 6th district from 1993 until her election to the U.S.",
    "D000216": "Rosa Luisa DeLauro ( dih-LOR-oh; born March 2, 1943) is an American politician serving as the U.S. representative for Connecticut's 3rd congressional district since 1991. She is a member of the Democratic Party. The district is based in New Haven and includes most of its suburbs.",
    "D000230": "Donald G. Davis is a member of the United States House of Representatives from NC.",
    "D000399": "Lloyd Doggett is a member of the United States House of Representatives from TX.",
    "D000530": "Christopher R. Deluzio is a member of the United States House of Representatives from PA.",
    "D000563": "Richard J. Durbin is a member of the United States Senate from IL.",
    "D000594": "Monica De La Cruz is a member of the United States House of Representatives from TX.",
    "D000600": "Mario Diaz-Balart is a member of the United States House of Representatives from FL.",
    "D000616": "Scott Eugene DesJarlais ( DAY-zhar-LAY; born February 21, 1964) is an American politician and physician serving as the U.S. representative for Tennessee's 4th congressional district since 2011. The district stretches across East and Middle Tennessee. He is a member of the Republican Party and a conservative.",
    "D000617": "Suzan K. DelBene is a member of the United States House of Representatives from WA.",
    "D000618": "Steve Daines is a member of the United States Senate from MT.",
    "D000622": "Tammy Duckworth is a member of the United States Senate from IL.",
    "D000623": "Mark DeSaulnier is a member of the United States House of Representatives from CA.",
    "D000624": "Deborah Ann Dingell ( DING-gəl; née Insley; November 23, 1953) is an American politician serving as a U.S. representative from Michigan since 2015, representing the state's 6th congressional district since 2023. A member of the Democratic Party, she succeeded her late husband, John Dingell, who was the longest-serving member of Congress in U.S. Dingell is active in several organizations in Michigan and Washington, D.C., and serves on a number of boards.",
    "D000626": "Warren Davidson is a member of the United States House of Representatives from OH.",
    "D000628": "Neal P. Dunn is a member of the United States House of Representatives from FL.",
    "D000629": "Sharice Lynnette Davids (; born May 22, 1980) is an American politician, attorney, and former mixed martial artist serving as the U.S. representative from Kansas's 3rd congressional district since 2019. A member of the Democratic Party, she represents a district that includes most of the Kansas side of the Kansas City metropolitan area, including Kansas City, Overland Park, Prairie Village, Leawood, Lenexa, and Olathe. Davids was elected in 2018 and became the first Democrat to represent a Kansas congressional district in a decade.",
    "D000631": "Madeleine Dean is a member of the United States House of Representatives from PA.",
    "D000634": "Troy Downing is a member of the United States House of Representatives from MT.",
    "D000635": "Maxine Elizabeth Dexter (née Johnson, born December 5, 1972) is an American physician and politician serving as the U.S. representative for Oregon's 3rd congressional district since 2025. The district includes most of Portland east of the Willamette River. A member of the Democratic Party, she previously represented the 33rd district of the Oregon House of Representatives from 2020 to 2024, which covers parts of Northwest Portland, as well as Cedar Mill, Oak Hills, and most of Bethany.",
    "E000071": "Jake Ellzey is a member of the United States House of Representatives from TX.",
    "E000235": "Mike Ezell is a member of the United States House of Representatives from MS.",
    "E000246": "Charles Marion Edwards is an American politician serving as the U.S. representative for North Carolina's 11th congressional district since 2023. A member of the Republican Party, he represented the 48th district in the North Carolina Senate from 2016 to 2023.",
    "E000294": "(born March 3, 1961) is an American attorney, lobbyist, and politician who has served as majority whip in the United States House of Representatives since 2023. A member of the Republican Party, he has represented Minnesota's 6th congressional district since 2015. During his tenure in Congress, he has been known as a strong advocate for the crypto industry. Before his election to Congress, Emmer served three terms as a member of the Minnesota House of Representatives from 2005 to 2011.",
    "E000295": "Joni Ernst is a member of the United States Senate from IA.",
    "E000296": "Dwight Evans is a member of the United States House of Representatives from PA.",
    "E000297": "Adriano Espaillat is a member of the United States House of Representatives from NY.",
    "E000298": "Ron Estes is a member of the United States House of Representatives from KS.",
    "E000299": "Veronica Escobar is a member of the United States House of Representatives from TX.",
    "E000300": "Gabe Evans is a member of the United States House of Representatives from CO.",
    "E000301": "Sarah Elfreth is a member of the United States House of Representatives from MD.",
    "F000110": "Cleo Fields is a member of the United States House of Representatives from LA.",
    "F000246": "Patrick Edward Fallon (born December 19, 1967) is an American businessman and politician. A member of the Republican Party, he has been the U.S. representative for Texas's 4th congressional district since 2021. Fallon was also a member of the Texas House of Representatives for the 106th district from 2013 to 2019 and represented the 30th district of the Texas Senate from 2019 to 2021.",
    "F000446": "Randy Feenstra is a member of the United States House of Representatives from IA.",
    "F000450": "Virginia Foxx is a member of the United States House of Representatives from NC.",
    "F000454": "Bill Foster is a member of the United States House of Representatives from IL.",
    "F000459": "Charles J. \"Chuck\" Fleischmann is a member of the United States House of Representatives from TN.",
    "F000462": "Lois Frankel is a member of the United States House of Representatives from FL.",
    "F000463": "Deb Fischer is a member of the United States Senate from NE.",
    "F000466": "Brian K. Fitzpatrick is a member of the United States House of Representatives from PA.",
    "F000468": "Lizzie Fletcher is a member of the United States House of Representatives from TX.",
    "F000469": "Russell Mark Fulcher (born March 9, 1962) is an American businessman and politician serving as the U.S. representative for Idaho's 1st congressional district since 2019. Previously, he served in the Idaho Senate from 2005 to 2014. A member of the Republican Party, Fulcher previously sought the party's nomination in the 2014 Idaho gubernatorial election, unsuccessfully challenging incumbent Butch Otter in the primary.",
    "F000470": "Michelle Fischbach is a member of the United States House of Representatives from MN.",
    "F000471": "Scott Fitzgerald is a member of the United States House of Representatives from WI.",
    "F000472": "Scott Franklin is a member of the United States House of Representatives from FL.",
    "F000474": "Mike Flood is a member of the United States House of Representatives from NE.",
    "F000475": "Brad Finstad is a member of the United States House of Representatives from MN.",
    "F000476": "Maxwell Frost is a member of the United States House of Representatives from FL.",
    "F000477": "Valerie P. Foushee is a member of the United States House of Representatives from NC.",
    "F000478": "Russell William Fry (born January 31, 1985) is an American politician and lawyer serving as the U.S. representative for South Carolina's 7th congressional district since 2023. A member of the Republican Party, Fry represented the 106th District in the South Carolina House of Representatives from 2015 to 2023. In 2018, he was appointed to the position of Majority Chief Whip for the 122nd South Carolina General Assembly.",
    "F000479": "John Fetterman is a member of the United States Senate from PA.",
    "F000480": "Vince Fong is a member of the United States House of Representatives from CA.",
    "F000481": "Shomari Figures is a member of the United States House of Representatives from AL.",
    "F000482": "Julie Fedorchak is a member of the United States House of Representatives from ND.",
    "F000483": "Laura Friedman is a member of the United States House of Representatives from CA.",
    "F000484": "Randy Fine is a member of the United States House of Representatives from FL.",
    "F000485": "Clay Fuller is a member of the United States House of Representatives from GA.",
    "G000359": "Lindsey Graham is a member of the United States Senate from SC.",
    "G000386": "Chuck Grassley is a member of the United States Senate from IA.",
    "G000546": "Sam Graves is a member of the United States House of Representatives from MO.",
    "G000553": "Albert Leornes Greene, known professionally as Al Green, is an American singer, songwriter, pastor and record producer. He is best known for recording a series of soul hit singles in the early 1970s, including \"Tired of Being Alone\" (1971), \"I'm Still in Love with You\" (1972), \"Love and Happiness\" (1973), \"Take Me to the River\" (1974), and his signature song, \"Let's Stay Together\" (1972). Green became an ordained pastor and recorded gospel music during the 1980s.",
    "G000555": "Kirsten E. Gillibrand is a member of the United States Senate from NY.",
    "G000558": "Brett Guthrie is a member of the United States House of Representatives from KY.",
    "G000559": "John Garamendi is a member of the United States House of Representatives from CA.",
    "G000565": "Paul A. Gosar is a member of the United States House of Representatives from AZ.",
    "G000568": "H. Morgan Griffith is a member of the United States House of Representatives from VA.",
    "G000574": "Ruben Gallego is a member of the United States Senate from AZ.",
    "G000576": "Glenn Grothman is a member of the United States House of Representatives from WI.",
    "G000581": "Vicente Gonzalez is a member of the United States House of Representatives from TX.",
    "G000583": "Josh Gottheimer is a member of the United States House of Representatives from NJ.",
    "G000585": "Jimmy Gomez is a member of the United States House of Representatives from CA.",
    "G000586": "\"Chuy\" García ( CHOO-ee; born April 12, 1956) is an American politician serving as the U.S. representative for Illinois's 4th district since 2019. A member of the Democratic Party, he served on the Cook County Board of Commissioners, as well as in the Illinois Senate and on the Chicago City Council before his election to Congress. He was also a candidate for mayor of Chicago in 2015 and 2023.",
    "G000587": "Sylvia R. Garcia is a member of the United States House of Representatives from TX.",
    "G000589": "Lance Gooden is a member of the United States House of Representatives from TX.",
    "G000591": "Michael Guest is a member of the United States House of Representatives from MS.",
    "G000592": "Jared F. Golden is a member of the United States House of Representatives from ME.",
    "G000593": "Carlos A. Gimenez is a member of the United States House of Representatives from FL.",
    "G000597": "Andrew R. Garbarino is a member of the United States House of Representatives from NY.",
    "G000598": "Robert Garcia is a member of the United States House of Representatives from CA.",
    "G000599": "Daniel S. Goldman is a member of the United States House of Representatives from NY.",
    "G000600": "Marie Gluesenkamp Perez is a member of the United States House of Representatives from WA.",
    "G000601": "Craig A. Goldman is a member of the United States House of Representatives from TX.",
    "G000602": "Laura Gillen is a member of the United States House of Representatives from NY.",
    "G000603": "Brandon Gill is a member of the United States House of Representatives from TX.",
    "G000604": "Maggie Goodlander is a member of the United States House of Representatives from NH.",
    "G000605": "Adam Gray is a member of the United States House of Representatives from CA.",
    "G000606": "Adelita S. Grijalva is a member of the United States House of Representatives from AZ.",
    "H000273": "John W. Hickenlooper is a member of the United States Senate from CO.",
    "H000601": "Bill Hagerty is a member of the United States Senate from TN.",
    "H000874": "Steny H. Hoyer is a member of the United States House of Representatives from MD.",
    "H001042": "Mazie K. Hirono is a member of the United States Senate from HI.",
    "H001046": "Martin Heinrich is a member of the United States Senate from NM.",
    "H001047": "James A. Himes is a member of the United States House of Representatives from CT.",
    "H001052": "Andy Harris is a member of the United States House of Representatives from MD.",
    "H001058": "Bill Huizenga is a member of the United States House of Representatives from MI.",
    "H001061": "John Henry Hoeven III is an American politician and banker serving as the senior U.S. senator from North Dakota, a seat he has held since 2011. A member of the Republican Party, Hoeven served as the 31st governor of North Dakota from 2000 to 2010.",
    "H001066": "Steven Horsford is a member of the United States House of Representatives from NV.",
    "H001067": "Richard Hudson is a member of the United States House of Representatives from NC.",
    "H001068": "Jared Huffman is a member of the United States House of Representatives from CA.",
    "H001072": "J. French Hill is a member of the United States House of Representatives from AR.",
    "H001076": "Margaret Wood Hassan is a member of the United States Senate from NH.",
    "H001077": "Clay Higgins is a member of the United States House of Representatives from LA.",
    "H001079": "Cindy Hyde-Smith is a member of the United States Senate from MS.",
    "H001081": "Jahana Hayes is a member of the United States House of Representatives from CT.",
    "H001082": "Kevin Hern is a member of the United States House of Representatives from OK.",
    "H001085": "Chrissy Houlahan is a member of the United States House of Representatives from PA.",
    "H001086": "Diana Lynn Harshbarger ( HARSH-bar-gər; born January 1, 1960) is an American pharmacist, businesswoman, and politician. Harshbarger has served as the U.S. representative for Tennessee's 1st congressional district since 2021. Her district is based in the Tri-Cities area in northeastern Tennessee.",
    "H001089": "Josh Hawley is a member of the United States Senate from MO.",
    "H001090": "Joshua Keck Harder is an American politician who has served as the U.S. representative for California's 9th congressional district since 2023, after representing the 10th district from 2019 to 2023. A member of the Democratic Party, he was first elected in 2018 by defeating Republican incumbent Jeff Denham. After the 2020 redistricting, he won reelection in the newly drawn 9th district, which covers the majority of San Joaquin County and includes Stockton, Tracy, Lodi, and Manteca.",
    "H001091": "Ashley Hinson is a member of the United States House of Representatives from IA.",
    "H001093": "Erin Houchin is a member of the United States House of Representatives from IN.",
    "H001094": "Val T. Hoyle is a member of the United States House of Representatives from OR.",
    "H001095": "Wesley Hunt is a member of the United States House of Representatives from TX.",
    "H001096": "Harriet M. Hageman is a member of the United States House of Representatives from WY.",
    "H001098": "Abraham J. Hamadeh is a member of the United States House of Representatives from AZ.",
    "H001099": "Mike Haridopolos is a member of the United States House of Representatives from FL.",
    "H001100": "Jeff Hurd is a member of the United States House of Representatives from CO.",
    "H001101": "Pat Harrigan is a member of the United States House of Representatives from NC.",
    "H001102": "Mark Harris is a member of the United States House of Representatives from NC.",
    "H001103": "Pablo José Hernández is a member of the United States House of Representatives from PR.",
    "H001104": "Jon Husted is a member of the United States Senate from OH.",
    "I000056": "Darrell Issa is a member of the United States House of Representatives from CA.",
    "I000058": "Glenn Ivey is a member of the United States House of Representatives from MD.",
    "J000288": "Henry C. \"Hank\" Johnson, Jr. is a member of the United States House of Representatives from GA.",
    "J000289": "Jim Jordan is a member of the United States House of Representatives from OH.",
    "J000293": "Ron Johnson is a member of the United States Senate from WI.",
    "J000294": "Hakeem S. Jeffries is a member of the United States House of Representatives from NY.",
    "J000295": "David P. Joyce is a member of the United States House of Representatives from OH.",
    "J000298": "Pramila Jayapal is a member of the United States House of Representatives from WA.",
    "J000299": "Mike Johnson is a member of the United States House of Representatives from LA.",
    "J000301": "Dusty Johnson is a member of the United States House of Representatives from SD.",
    "J000302": "John Joyce is a member of the United States House of Representatives from PA.",
    "J000304": "Ronny Lynn Jackson (born May 4, 1967) is an American physician, politician, and former United States Navy officer who has served as the U.S. representative for Texas's 13th congressional district since 2021. A member of the Republican Party, his district is based in Amarillo and includes the Texas panhandle and much of northeast Texas, as far as Denton. Jackson joined the White House Medical Unit in the mid-2000s under George W.",
    "J000305": "Sara Jacobs is a member of the United States House of Representatives from CA.",
    "J000307": "John James is a member of the United States House of Representatives from MI.",
    "J000309": "Jonathan L. Jackson is a member of the United States House of Representatives from IL.",
    "J000310": "Julie Johnson is a member of the United States House of Representatives from TX.",
    "J000311": "Brian Jack is a member of the United States House of Representatives from GA.",
    "J000312": "James C. Justice is a member of the United States Senate from WV.",
    "K000009": "Marcy Kaptur is a member of the United States House of Representatives from OH.",
    "K000367": "Amy Jean Klobuchar ( KLOH-bə-shar; born May 25, 1960) is an American politician and lawyer serving as the senior United States senator from Minnesota, a seat she has held since 2007. A member of the Minnesota Democratic–Farmer–Labor Party (DFL), Minnesota's affiliate of the Democratic Party, she previously served as county attorney of Hennepin County, Minnesota. She is running for governor of Minnesota in the 2026 election. Born in Plymouth, Minnesota, Klobuchar graduated from Yale University and the University of Chicago Law School.",
    "K000375": "William R. Keating is a member of the United States House of Representatives from MA.",
    "K000376": "Mike Kelly is a member of the United States House of Representatives from PA.",
    "K000377": "Mark Kelly is a member of the United States Senate from AZ.",
    "K000383": "Angus S. King, Jr. is a member of the United States Senate from ME.",
    "K000384": "Tim Kaine is a member of the United States Senate from VA.",
    "K000385": "Robin L. Kelly is a member of the United States House of Representatives from IL.",
    "K000388": "Trent Kelly is a member of the United States House of Representatives from MS.",
    "K000389": "Rohit \"Ro\" Khanna is an American politician and attorney serving as the U.S. representative from California's 17th congressional district since 2017. A member of the Democratic Party, he defeated eight-term incumbent Democratic representative Mike Honda in the 2016 general election, after first running for the same seat in 2014. Khanna also served as the deputy assistant secretary in the United States Department of Commerce under President Barack Obama from 2009 to 2011.",
    "K000391": "Raja Krishnamoorthi is a member of the United States House of Representatives from IL.",
    "K000392": "David Kustoff is a member of the United States House of Representatives from TN.",
    "K000393": "John Kennedy is a member of the United States Senate from LA.",
    "K000394": "Andy Kim is a member of the United States Senate from NJ.",
    "K000397": "Young Kim is a member of the United States House of Representatives from CA.",
    "K000398": "Thomas H. Kean, Jr. is a member of the United States House of Representatives from NJ.",
    "K000399": "Jennifer A. Kiggans is a member of the United States House of Representatives from VA.",
    "K000400": "Sydney Kamlager-Dove is a member of the United States House of Representatives from CA.",
    "K000401": "Kevin Kiley may refer to:Kevin C. Kiley, United States Army general\nKevin F. Kiley, American military historian\nKevin Kiley (sportscaster), American sportscaster and talk show host\nKevin Kiley (wrestler), American wrestler formerly known as Alex Riley\nKevin Kiley (politician), U.S. representative for California's 3rd congressional district",
    "K000402": "Timothy M. Kennedy is a member of the United States House of Representatives from NY.",
    "K000403": "Mike Kennedy is a member of the United States House of Representatives from UT.",
    "K000404": "Kimberlyn King-Hinds is a member of the United States House of Representatives from MP.",
    "K000405": "Brad Knott is a member of the United States House of Representatives from NC.",
    "L000273": "Teresa Leger Fernandez is a member of the United States House of Representatives from NM.",
    "L000397": "Zoe Lofgren is a member of the United States House of Representatives from CA.",
    "L000491": "Frank D. Lucas is a member of the United States House of Representatives from OK.",
    "L000557": "John B. Larson is a member of the United States House of Representatives from CT.",
    "L000560": "Rick Larsen is a member of the United States House of Representatives from WA.",
    "L000562": "Stephen F. Lynch is a member of the United States House of Representatives from MA.",
    "L000566": "Robert E. Latta is a member of the United States House of Representatives from OH.",
    "L000570": "Ben Ray Luján is a member of the United States Senate from NM.",
    "L000571": "Cynthia M. Lummis is a member of the United States Senate from WY.",
    "L000575": "James Lankford is a member of the United States Senate from OK.",
    "L000577": "Mike Lee is a member of the United States Senate from UT.",
    "L000582": "Ted Lieu is a member of the United States House of Representatives from CA.",
    "L000583": "Barry Loudermilk is a member of the United States House of Representatives from GA.",
    "L000585": "Darin LaHood is a member of the United States House of Representatives from IL.",
    "L000590": "Susie Lee is a member of the United States House of Representatives from NV.",
    "L000593": "Mike Levin is a member of the United States House of Representatives from CA.",
    "L000595": "Julia Janelle Letlow is an American politician and academic administrator serving as the U.S. representative for Louisiana's 5th congressional district since 2021. Letlow is the first Republican woman to represent Louisiana in the House.",
    "L000596": "Anna Paulina Luna is a member of the United States House of Representatives from FL.",
    "L000597": "Laurel M. Lee is a member of the United States House of Representatives from FL.",
    "L000598": "Nick LaLota is a member of the United States House of Representatives from NY.",
    "L000599": "Michael Lawler is a member of the United States House of Representatives from NY.",
    "L000600": "Nicholas A. Langworthy is a member of the United States House of Representatives from NY.",
    "L000601": "Greg Landsman is a member of the United States House of Representatives from OH.",
    "L000602": "Summer L. Lee is a member of the United States House of Representatives from PA.",
    "L000603": "Morgan Luttrell is a member of the United States House of Representatives from TX.",
    "L000606": "George Latimer may refer to: George Latimer (escaped slave) (1819–c. 1896), escaped slave whose case became a major political issue in Massachusetts George Latimer (Minnesota politician) (1935–2024), mayor of St. Paul, Minnesota George Latimer (New York politician) (born 1953), U.S. representative from New York George Latimer (Pennsylvania politician) (1750–1825), Speaker of the Pennsylvania House of Representatives George W.",
    "L000607": "Sam T. Liccardo is a member of the United States House of Representatives from CA.",
    "M000133": "Edward J. Markey is a member of the United States Senate from MA.",
    "M000194": "Nancy Ruth Mace (born December 4, 1977) is an American politician serving as the U.S. representative for South Carolina's 1st congressional district since 2021. A member of the Republican Party, she previously served in the South Carolina General Assembly from 2018 to 2020. In 1999, Mace became the first woman to graduate from the Corps of Cadets program at the Citadel Military College of South Carolina, which was led at the time by her father, Emory Mace, the commandant of cadets.",
    "M000312": "James P. McGovern is a member of the United States House of Representatives from MA.",
    "M000317": "Nicole Malliotakis ( MAL-ee-ə-TAH-kiss; born November 11, 1980) is an American politician serving as the U.S. representative for New York's 11th congressional district. Her district covers Staten Island and a portion of southern Brooklyn. A Republican, Malliotakis was first elected to the New York State Assembly in 2010.",
    "M000355": "Mitch McConnell is a member of the United States Senate from KY.",
    "M000687": "Kweisi Mfume is a member of the United States House of Representatives from MD.",
    "M000871": "Tracey Mann is a member of the United States House of Representatives from KS.",
    "M000934": "Jerry Moran is a member of the United States Senate from KS.",
    "M001111": "Patty Murray is a member of the United States Senate from WA.",
    "M001136": "Lisa C. McClain is a member of the United States House of Representatives from MI.",
    "M001137": "Gregory W. Meeks is a member of the United States House of Representatives from NY.",
    "M001143": "Betty McCollum is a member of the United States House of Representatives from MN.",
    "M001153": "Lisa Murkowski is a member of the United States Senate from AK.",
    "M001157": "Michael T. McCaul is a member of the United States House of Representatives from TX.",
    "M001160": "Gwen Moore is a member of the United States House of Representatives from WI.",
    "M001163": "Doris O. Matsui is a member of the United States House of Representatives from CA.",
    "M001169": "Christopher Murphy is a member of the United States Senate from CT.",
    "M001176": "Jeffrey Alan Merkley is an American politician who is the junior United States senator from Oregon. He was first elected to the Senate in 2008. A member of the Democratic Party, he previously served from 1999 to 2009 as the representative for the 47th district in the Oregon House of Representatives, which covers central Multnomah County, including portions of eastern Portland; he was the speaker of the Oregon House of Representatives during the last two years of his tenure.",
    "M001177": "Tom McClintock is a member of the United States House of Representatives from CA.",
    "M001184": "Thomas Massie is a member of the United States House of Representatives from KY.",
    "M001188": "Grace Meng is a member of the United States House of Representatives from NY.",
    "M001194": "John Robert Moolenaar ( MOHL-ən-ar; born May 8, 1961) is an American politician serving as a U.S. representative from Michigan since 2015, representing the 4th district from 2015 to 2023 and the 2nd congressional district since 2023. A member of the Republican Party, he served in the Michigan House of Representatives from 2003 to 2008 and the Michigan Senate from 2011 to 2014. Early life and education Moolenaar was born on May 8, 1961, in Midland, Michigan.",
    "M001196": "Seth Wilbur Moulton (born October 24, 1978) is an American politician and Marine Corps combat veteran who has been the U.S. representative for Massachusetts's 6th congressional district since 2015. A member of the Democratic Party, his district includes many of Boston's northern suburbs, such as Andover, Marblehead, Peabody, and his hometown of Salem. After graduating from Harvard College in 2001 with a bachelor of science in physics, Moulton joined the United States Marine Corps.",
    "M001198": "Roger Marshall is a member of the United States Senate from KS.",
    "M001199": "Brian J. Mast is a member of the United States House of Representatives from FL.",
    "M001204": "Daniel Meuser is a member of the United States House of Representatives from PA.",
    "M001205": "Carol D. Miller is a member of the United States House of Representatives from WV.",
    "M001206": "Joseph D. Morelle is a member of the United States House of Representatives from NY.",
    "M001208": "Lucy McBath is a member of the United States House of Representatives from GA.",
    "M001210": "Gregory F. Murphy is a member of the United States House of Representatives from NC.",
    "M001211": "Mary E. Miller is a member of the United States House of Representatives from IL.",
    "M001212": "Barry Moore is a member of the United States House of Representatives from AL.",
    "M001213": "Blake D. Moore is a member of the United States House of Representatives from UT.",
    "M001214": "Frank J. Mrvan is a member of the United States House of Representatives from IN.",
    "M001215": "Mariannette Miller-Meeks is a member of the United States House of Representatives from IA.",
    "M001216": "Cory Mills is a member of the United States House of Representatives from FL.",
    "M001217": "Jared Moskowitz is a member of the United States House of Representatives from FL.",
    "M001218": "Richard McCormick is a member of the United States House of Representatives from GA.",
    "M001219": "James C. Moylan is a member of the United States House of Representatives from GU.",
    "M001220": "Morgan McGarvey is a member of the United States House of Representatives from KY.",
    "M001222": "Max L. Miller is a member of the United States House of Representatives from OH.",
    "M001223": "Seth Michael Magaziner ( mag-ə-ZEE-nər; born July 22, 1983) is an American investment professional and politician serving as the U.S. representative for Rhode Island's 2nd congressional district since 2023. A member of the Democratic Party, he previously served as the 31st general treasurer of Rhode Island from 2015 until 2023. Magaziner won the November 2022 election to succeed retiring representative James Langevin.",
    "M001224": "Nathaniel Moran is a member of the United States House of Representatives from TX.",
    "M001225": "Kevin Mullin is a member of the United States House of Representatives from CA.",
    "M001226": "Robert Menendez is a member of the United States House of Representatives from NJ.",
    "M001227": "Jennifer L. McClellan is a member of the United States House of Representatives from VA.",
    "M001228": "Celeste Maloy is a member of the United States House of Representatives from UT.",
    "M001229": "LaMonica McIver is a member of the United States House of Representatives from NJ.",
    "M001230": "Ryan Edward Mackenzie (born August 3, 1982) is an American politician serving as the U.S. representative from Pennsylvania's 7th congressional district since 2025. A member of the Republican Party, he served in the Pennsylvania House of Representatives from 2012 to 2024. Before redistricting, he represented the 134th district until his final term, when he was moved to the 187th district.",
    "M001231": "John W. Mannion is a member of the United States House of Representatives from NY.",
    "M001232": "April Lynn McClain Delaney is an American lawyer and politician who is a member of the U.S. House of Representatives representing Maryland's 6th congressional district since 2025. She previously served as the deputy administrator of the National Telecommunications and Information Administration from 2022 to 2023.",
    "M001233": "Mark B. Messmer is a member of the United States House of Representatives from IN.",
    "M001234": "Kelly Morrison is a member of the United States House of Representatives from MN.",
    "M001235": "Riley M. Moore is a member of the United States House of Representatives from WV.",
    "M001236": "Tim Moore is a member of the United States House of Representatives from NC.",
    "M001237": "Kristen McDonald Rivet is a member of the United States House of Representatives from MI.",
    "M001238": "Sarah McBride is a member of the United States House of Representatives from DE.",
    "M001239": "John J. McGuire III is a member of the United States House of Representatives from VA.",
    "M001240": "Addison P. McDowell is a member of the United States House of Representatives from NC.",
    "M001241": "Dave Min is a member of the United States House of Representatives from CA.",
    "M001242": "Bernie Moreno is a member of the United States Senate from OH.",
    "M001243": "David McCormick is a member of the United States Senate from PA.",
    "M001244": "Ashley Moody is a member of the United States Senate from FL.",
    "M001245": "Christian D. Menefee is a member of the United States House of Representatives from TX.",
    "N000002": "Jerrold Nadler is a member of the United States House of Representatives from NY.",
    "N000015": "Richard E. Neal is a member of the United States House of Representatives from MA.",
    "N000026": "Troy E. Nehls is a member of the United States House of Representatives from TX.",
    "N000147": "Eleanor Holmes Norton is a member of the United States House of Representatives from DC.",
    "N000188": "Donald Norcross is a member of the United States House of Representatives from NJ.",
    "N000189": "Dan Newhouse is a member of the United States House of Representatives from WA.",
    "N000190": "Ralph Norman is a member of the United States House of Representatives from SC.",
    "N000191": "Joe Neguse is a member of the United States House of Representatives from CO.",
    "N000193": "Zachary Nunn is a member of the United States House of Representatives from IA.",
    "O000019": "Jay Obernolte is a member of the United States House of Representatives from CA.",
    "O000086": "Burgess Owens is a member of the United States House of Representatives from UT.",
    "O000172": "Alexandria Ocasio-Cortez is a member of the United States House of Representatives from NY.",
    "O000173": "Ilhan Omar is a member of the United States House of Representatives from MN.",
    "O000174": "Jon Ossoff is a member of the United States Senate from GA.",
    "O000175": "Andrew Ogles is a member of the United States House of Representatives from TN.",
    "O000176": "Johnny Olszewski, Jr. is a member of the United States House of Representatives from MD.",
    "O000177": "Robert F. Onder, Jr. is a member of the United States House of Representatives from MO.",
    "P000034": "Frank Pallone, Jr. is a member of the United States House of Representatives from NJ.",
    "P000048": "August Lee Pfluger ( FLOO-gər; born December 28, 1977) is an American politician and Air Force officer serving as the U.S. representative for Texas's 11th congressional district since 2021. A member of the Republican Party, his district includes much of West Texas. Early life and education Pfluger's four-times-great-grandfather, German immigrant Henry Pfluger Sr.",
    "P000145": "Alex Padilla is a member of the United States Senate from CA.",
    "P000197": "Nancy Pelosi is a member of the United States House of Representatives from CA.",
    "P000595": "Gary Charles Peters is an American politician, lawyer, and former naval officer serving as the senior United States senator from Michigan, a seat he has held since 2015. A member of the Democratic Party, he was the U.S. representative for Michigan's 14th congressional district, which included the eastern half of Detroit, the Grosse Pointes, Hamtramck, Southfield, and Pontiac, from 2009 to 2015.",
    "P000597": "Chellie Pingree is a member of the United States House of Representatives from ME.",
    "P000603": "Rand Paul is a member of the United States Senate from KY.",
    "P000605": "Scott Perry is a member of the United States House of Representatives from PA.",
    "P000607": "Mark Pocan is a member of the United States House of Representatives from WI.",
    "P000608": "Scott H. Peters is a member of the United States House of Representatives from CA.",
    "P000609": "Gary J. Palmer is a member of the United States House of Representatives from AL.",
    "P000610": "Stacey E. Plaskett is a member of the United States House of Representatives from VI.",
    "P000613": "Jimmy Panetta is a member of the United States House of Representatives from CA.",
    "P000614": "Chris Pappas is a member of the United States House of Representatives from NH.",
    "P000617": "Ayanna Soyini Pressley (born February 3, 1974) is an American politician who has served as the U.S. representative for Massachusetts's 7th congressional district since 2019. This district includes the northern three quarters of Boston, most of Cambridge, parts of Milton, as well as all of Chelsea, Everett, Randolph, and Somerville. Pressley served as an at-large member of the Boston City Council from 2010 through 2019.",
    "P000620": "Brittany Pettersen is a member of the United States House of Representatives from CO.",
    "P000621": "Nellie Pou is a member of the United States House of Representatives from NJ.",
    "P000622": "Jimmy Patronis is a member of the United States House of Representatives from FL.",
    "Q000023": "Mike Quigley is a member of the United States House of Representatives from IL.",
    "R000122": "Jack Reed is a member of the United States Senate from RI.",
    "R000305": "Deborah K. Ross is a member of the United States House of Representatives from NC.",
    "R000395": "Harold Dallas Rogers is an American lawyer and politician serving as the U.S. representative for Kentucky's 5th congressional district since 1981. He is a member of the Republican Party. Upon Don Young's death in 2022, Rogers became the dean of the House of Representatives.",
    "R000575": "Mike Rogers is a member of the United States House of Representatives from AL.",
    "R000579": "Patrick Ryan is a member of the United States House of Representatives from NY.",
    "R000584": "James E. Risch is a member of the United States Senate from ID.",
    "R000599": "Raul Ruiz is a member of the United States House of Representatives from CA.",
    "R000600": "Aumua Amata Coleman Radewagen is a member of the United States House of Representatives from AS.",
    "R000603": "David Cheston Rouzer ( ROW-zər; born February 16, 1972) is an American politician who is the U.S. representative for North Carolina's 7th congressional district. Previously he was a Republican member of the North Carolina General Assembly, representing Johnston County and Wayne County in the 12th district of the North Carolina Senate. Early life, education, and business career Rouzer was born at Landstuhl Army Medical Center in Landstuhl, West Germany (now Germany), where his father was based, in 1972.",
    "R000605": "Marion Michael Rounds is an American businessman and politician serving as the junior United States senator from South Dakota since 2015. A member of the Republican Party, he served as the 31st governor of South Dakota from 2003 to 2011.",
    "R000606": "Jamie Raskin is a member of the United States House of Representatives from MD.",
    "R000608": "Jacky Rosen is a member of the United States Senate from NV.",
    "R000609": "John H. Rutherford is a member of the United States House of Representatives from FL.",
    "R000610": "Guy Reschenthaler is a member of the United States House of Representatives from PA.",
    "R000612": "John W. Rose is a member of the United States House of Representatives from TN.",
    "R000614": "Chip Roy is a member of the United States House of Representatives from TX.",
    "R000617": "Delia C. Ramirez is a member of the United States House of Representatives from IL.",
    "R000618": "Pete Ricketts is a member of the United States Senate from NE.",
    "R000619": "Michael A. Rulli is a member of the United States House of Representatives from OH.",
    "R000620": "Luz M. Rivas is a member of the United States House of Representatives from CA.",
    "R000621": "Emily Randall is a member of the United States House of Representatives from WA.",
    "R000622": "Joshua Paul Riley (born January 21, 1981) is an American politician and lawyer who has served as the U.S. representative for New York's 19th congressional district since 2025. A member of the Democratic Party, he previously worked as a policy analyst at the U.S. Department of Labor and as counsel on the U.S.",
    "S000033": "Bernard Sanders (born September 8, 1941) is an American politician and activist serving as the senior United States senator from Vermont, a seat he has held since 2007. He is the longest-serving independent in U.S. congressional history, but maintains a close relationship with the Democratic Party, having caucused with House and Senate Democrats for most of his congressional career and sought the party's presidential nomination in 2016 and 2020. A self-described democratic socialist, Sanders is regarded as one of the main leaders of the 21st-century American progressive movement.",
    "S000148": "Charles E. Schumer is a member of the United States Senate from NY.",
    "S000168": "Maria Elvira Salazar is a member of the United States House of Representatives from FL.",
    "S000185": "Robert C. \"Bobby\" Scott is a member of the United States House of Representatives from VA.",
    "S000250": "Pete Sessions is a member of the United States House of Representatives from TX.",
    "S000344": "Brad Sherman is a member of the United States House of Representatives from CA.",
    "S000510": "Adam Smith (baptised 16 June [O.S. 5 June] 1723 – 17 July 1790) was a Scottish economist and philosopher who was a pioneer in the field of political economy and key figure during the Scottish Enlightenment. Seen by many as the \"father of economics\", or the \"father of capitalism\", he is primarily known for two classic works: The Theory of Moral Sentiments (1759) and An Inquiry into the Nature and Causes of the Wealth of Nations (1776). The latter, often abbreviated as The Wealth of Nations, is regarded as his magnum opus, marking the inception of modern economic scholarship as a comprehensive system and an academic discipline.",
    "S000522": "Chris Smith may refer to: Arts and entertainment Music Chris Smith (composer) (1879–1949), American composer and performer Chris \"Frenchie\" Smith, American record producer and musician Chris \"Daddy Mac\" Smith, member of rap music duo Kris Kross Chris Smith, lead guitarist/vocalist in the band Keelhaul Chris Smith, vocalist in Mythology Chris Smith, touring drums in Short Stack Chris Smith, keyboardist in Jefferson Starship Chris Smith, drummer and producer, member of The Internet Other media Chris Smith (broadcaster), Australian talkback radio broadcaster and radio host Chris Smith (filmmaker) (born 1970), American filmmaker Chris Smith (newsreader), British author and radio journalist Chris Smith (EastEnders), fictional soap opera character Politics Chris Smith (New Jersey politician) (born 1953), U.S. Representative from New Jersey Chris Smith (Florida politician) (born 1970), Florida state senator Chris Smith, Baron Smith of Finsbury (born 1951), former British Member of Parliament and government minister Sports Association football Chris Smith (footballer, born 1981), English footballer Chris Smith (footballer, born 1986), Scottish footballer...",
    "S000929": "Victoria Spartz is a member of the United States House of Representatives from IN.",
    "S001145": "Janice D. Schakowsky is a member of the United States House of Representatives from IL.",
    "S001148": "Michael K. Simpson is a member of the United States House of Representatives from ID.",
    "S001150": "Adam B. Schiff is a member of the United States Senate from CA.",
    "S001156": "Linda T. Sánchez is a member of the United States House of Representatives from CA.",
    "S001159": "Marilyn Strickland is a member of the United States House of Representatives from WA.",
    "S001172": "Adrian Smith may refer to: Adrian Smith (basketball) (1936–2026), American basketball player Adrian Smith (architect) (born 1944), American architect Sir Adrian Smith (statistician) (born 1946), English statistician and academic Adrian Smith (musician) (born 1957), English musician, member of the band Iron Maiden Adrian Smith (strongman) (born 1964), British professional strongman competitor Adrian Smith (politician) (born 1970), United States representative from Nebraska's 3rd congressional district Adrian Smith (illustrator), British illustrator of game materials Adrian Smith (rugby union) (born 1987), New Zealand rugby player",
    "S001176": "Stephen Joseph Scalise is an American politician who has been the House majority leader since 2023 and the U.S. representative for Louisiana's 1st congressional district since 2008. A member of the Republican Party, he was the House majority whip from 2014 to 2019 and the House minority whip 2019 to 2023.",
    "S001181": "Jeanne Shaheen is a member of the United States Senate from NH.",
    "S001183": "David Schweikert is a member of the United States House of Representatives from AZ.",
    "S001184": "Tim Scott is a member of the United States Senate from SC.",
    "S001185": "Terri A. Sewell is a member of the United States House of Representatives from AL.",
    "S001188": "Marlin A. Stutzman is a member of the United States House of Representatives from IN.",
    "S001189": "Austin Scott is a member of the United States House of Representatives from GA.",
    "S001190": "Bradley Scott Schneider is a member of the United States House of Representatives from IL.",
    "S001194": "Brian Schatz is a member of the United States Senate from HI.",
    "S001195": "Jason Smith is a member of the United States House of Representatives from MO.",
    "S001196": "Elise Marie Stefanik ( stə-FAH-nik; born July 2, 1984) is an American politician who has served as the U.S. representative for New York's 21st congressional district since 2015. From 2021 to 2025, she served as chair of the House Republican Conference. Stefanik was elected as a moderate Republican but aligned herself with Donald Trump during his first term as president.",
    "S001198": "Dan Sullivan is a member of the United States Senate from AK.",
    "S001199": "Lloyd Smucker is a member of the United States House of Representatives from PA.",
    "S001200": "Darren Soto is a member of the United States House of Representatives from FL.",
    "S001201": "Thomas R. Suozzi is a member of the United States House of Representatives from NY.",
    "S001203": "Tina Smith is a member of the United States Senate from MN.",
    "S001205": "Mary Gay Scanlon is a member of the United States House of Representatives from PA.",
    "S001208": "Elissa Slotkin is a member of the United States Senate from MI.",
    "S001211": "Greg Stanton is a member of the United States House of Representatives from AZ.",
    "S001212": "Pete Stauber is a member of the United States House of Representatives from MN.",
    "S001213": "Bryan Steil is a member of the United States House of Representatives from WI.",
    "S001214": "W. Gregory Steube is a member of the United States House of Representatives from FL.",
    "S001215": "Haley M. Stevens is a member of the United States House of Representatives from MI.",
    "S001216": "Kim Schrier is a member of the United States House of Representatives from WA.",
    "S001217": "Rick Scott is a member of the United States Senate from FL.",
    "S001218": "Melanie A. Stansbury is a member of the United States House of Representatives from NM.",
    "S001220": "Dale W. Strong is a member of the United States House of Representatives from AL.",
    "S001221": "Hillary J. Scholten is a member of the United States House of Representatives from MI.",
    "S001223": "Emilia Strong Sykes is a member of the United States House of Representatives from OH.",
    "S001224": "Keith Self is a member of the United States House of Representatives from TX.",
    "S001225": "Eric Sorensen is a member of the United States House of Representatives from IL.",
    "S001226": "Andrea Rose Salinas (born December 6, 1969) is an American politician serving as the U.S. representative for Oregon's 6th congressional district since 2023. Oregon's 6th congressional district includes all of Yamhill and Polk counties, the part of Marion County that includes Salem and Woodburn, a small piece of Beaverton, and the suburban communities to the southwest of Portland, including Tigard, Tualatin, and Sherwood. A member of the Democratic Party, Salinas previously served as the Oregon State Representative for the 38th district, which includes the City of Lake Oswego and portions of southwestern Portland, from 2017 to 2023.",
    "S001227": "Eric Schmitt is a member of the United States Senate from MO.",
    "S001228": "Derek Schmidt is a member of the United States House of Representatives from KS.",
    "S001229": "Jefferson Shreve is a member of the United States House of Representatives from IN.",
    "S001230": "Suhas Subramanyam is a member of the United States House of Representatives from VA.",
    "S001231": "Lateefah Simon is a member of the United States House of Representatives from CA.",
    "S001232": "Tim Sheehy is a member of the United States Senate from MT.",
    "T000165": "Thomas P. Tiffany is a member of the United States House of Representatives from WI.",
    "T000193": "Bennie G. Thompson is a member of the United States House of Representatives from MS.",
    "T000250": "John Randolph Thune ( THOON; born January 7, 1961) is an American politician serving as the senior United States senator from South Dakota, a seat he has held since 2005. A member of the Republican Party, Thune has served since 2025 as Senate majority leader and Senate Republican leader. From 1997 to 2003, Thune served as the U.S. representative for South Dakota's at-large congressional district.",
    "T000278": "Tommy Tuberville is a member of the United States Senate from AL.",
    "T000460": "Charles Michael Thompson (born January 24, 1951) is an American politician serving as the U.S. representative for California's 4th congressional district (known as the 1st congressional district until 2013, and the California's 5th congressional district until 2023) since 1999. The district, in the outer northern portion of the San Francisco Bay Area, includes all of Lake and Napa counties and parts of Contra Costa, Solano, Yolo and Sonoma counties. Thompson chairs the House Gun Violence Prevention Task Force.",
    "T000463": "Michael R. Turner is a member of the United States House of Representatives from OH.",
    "T000467": "Glenn Thompson may refer to: Glenn Thompson (publisher) (1940–2001), American book publisher and activist Glenn Thompson (politician) (born 1959), American politician Glenn Thompson (musician) (born 1964), Australian musician Glenn Thompson (cricketer) (born 1969), English cricketer See also Glen Thomson (born 1973), cyclist",
    "T000468": "Dina Titus is a member of the United States House of Representatives from NV.",
    "T000469": "Paul David Tonko ( TONK-oh; born June 18, 1949) is an American politician serving as the U.S. representative for New York's 20th congressional district since 2013. He represented the 21st congressional district from 2009 to 2013. A member of the Democratic Party, Tonko has been called a staunch progressive.",
    "T000472": "Mark Takano is a member of the United States House of Representatives from CA.",
    "T000474": "Norma J. Torres is a member of the United States House of Representatives from CA.",
    "T000476": "Thom Tillis is a member of the United States Senate from NC.",
    "T000478": "Claudia Tenney is a member of the United States House of Representatives from NY.",
    "T000480": "William R. Timmons IV is a member of the United States House of Representatives from SC.",
    "T000481": "Rashida Tlaib is a member of the United States House of Representatives from MI.",
    "T000482": "Lori Ann Trahan ( trə-HANN; née Loureiro; born October 27, 1973) is an American businesswoman and politician serving as the U.S. representative for Massachusetts's 3rd congressional district since 2019. The district covers Boston's northwestern suburbs, and includes Lowell, Lawrence, Concord, and Trahan's hometown, Westford. A Democrat, she formerly served as chief of staff to Representative Marty Meehan in Massachusetts's 5th congressional district.",
    "T000486": "Ritchie John Torres (born March 12, 1988) is an American politician serving as the U.S. representative for New York's 15th congressional district since 2021. A member of the Democratic Party, he previously served on the New York City Council from 2014 to 2020. Torres served as the New York City Council member for the 15th district from 2014 to 2020.",
    "T000487": "Jill N. Tokuda is a member of the United States House of Representatives from HI.",
    "T000488": "Shri Thanedar is a member of the United States House of Representatives from MI.",
    "T000490": "David J. Taylor is a member of the United States House of Representatives from OH.",
    "T000491": "Derek Tran is a member of the United States House of Representatives from CA.",
    "U000040": "Lauren Ashley Underwood (born October 4, 1986) is an American politician and registered nurse who is a U.S. representative from Illinois's 14th congressional district as a member of the Democratic Party. Her district, once represented by former House speaker Dennis Hastert, includes the outer western suburbs of Chicago, including DeKalb, Joliet, Oswego, Ottawa, and Yorkville. Underwood grew up in Naperville, Illinois.",
    "V000081": "Nydia M. Velázquez is a member of the United States House of Representatives from NY.",
    "V000128": "Chris Van Hollen is a member of the United States Senate from MD.",
    "V000129": "David G. Valadao is a member of the United States House of Representatives from CA.",
    "V000130": "Juan Vargas is a member of the United States House of Representatives from CA.",
    "V000131": "Marc A. Veasey is a member of the United States House of Representatives from TX.",
    "V000133": "Jefferson Van Drew is a member of the United States House of Representatives from NJ.",
    "V000134": "Beth Van Duyne is a member of the United States House of Representatives from TX.",
    "V000135": "Derrick Van Orden is a member of the United States House of Representatives from WI.",
    "V000136": "Gabe Vasquez is a member of the United States House of Representatives from NM.",
    "V000138": "Eugene Simon Vindman is a member of the United States House of Representatives from VA.",
    "V000139": "Matt Van Epps is a member of the United States House of Representatives from TN.",
    "W000187": "Maxine Waters is a member of the United States House of Representatives from CA.",
    "W000437": "Roger Frederick Wicker (born July 5, 1951) is an American politician, attorney, and former Air Force officer serving as the senior United States senator from Mississippi, a seat he has held since 2007. A member of the Republican Party, Wicker was a Mississippi State Senator from 1988 to 1995 and the U.S. representative from Mississippi's 1st congressional district from 1995 until 2007. Born in Pontotoc, Mississippi, Wicker is a graduate of the University of Mississippi and the University of Mississippi School of Law.",
    "W000779": "Ronald Lee Wyden is an American attorney and politician serving as the senior United States senator from Oregon, a seat he has held since 1996. A member of the Democratic Party, he served in the United States House of Representatives from 1981 until 1996. Upon the death of Representative Don Young in 2022, Wyden became the dean of the West Coast's Congressional delegation. He is the dean of Oregon's congressional delegation and serves as the ranking member of the Senate Finance Committee.",
    "W000788": "Nikema Williams is a member of the United States House of Representatives from GA.",
    "W000790": "Raphael G. Warnock is a member of the United States Senate from GA.",
    "W000795": "Joe Wilson is a member of the United States House of Representatives from SC.",
    "W000797": "Debbie Wasserman Schultz is a member of the United States House of Representatives from FL.",
    "W000798": "Tim Walberg is a member of the United States House of Representatives from MI.",
    "W000800": "Peter Welch is a member of the United States Senate from VT.",
    "W000802": "Sheldon Whitehouse (born October 20, 1955) is an American politician and attorney serving as the junior United States senator from Rhode Island, a seat he has held since 2007. A member of the Democratic Party, he served as the United States Attorney for the District of Rhode Island from 1993 to 1998, and as the 71st attorney general of Rhode Island from 1999 to 2003. He was elected to the Senate in 2006, defeating Republican incumbent Lincoln Chafee. He was reelected in 2012, 2018, and 2024.",
    "W000804": "Robert J. Wittman is a member of the United States House of Representatives from VA.",
    "W000805": "Mark R. Warner is a member of the United States Senate from VA.",
    "W000806": "Daniel Webster was an American lawyer, statesman, and diplomat who represented New Hampshire and Massachusetts in the U.S. Congress and served as the 14th and 19th U.S. secretary of state under presidents William Henry Harrison, John Tyler, and Millard Fillmore. Webster was one of the most prominent American lawyers of the 19th century, arguing over 200 cases before the United States Supreme Court in his career.",
    "W000808": "Frederica S. Wilson is a member of the United States House of Representatives from FL.",
    "W000809": "Steve Womack is a member of the United States House of Representatives from AR.",
    "W000812": "Ann Wagner is a member of the United States House of Representatives from MO.",
    "W000814": "Randy K. Weber, Sr. is a member of the United States House of Representatives from TX.",
    "W000816": "Roger Williams is a member of the United States House of Representatives from TX.",
    "W000817": "Elizabeth Warren is a member of the United States Senate from MA.",
    "W000821": "Bruce Westerman is a member of the United States House of Representatives from AR.",
    "W000822": "Bonnie Marie Watson Coleman (born February 6, 1945) is an American politician serving as the U.S. representative for New Jersey's 12th congressional district since 2015. A member of the Democratic Party, Watson Coleman is the first African-American woman to represent New Jersey in the U.S. Watson Coleman was born in Camden, New Jersey.",
    "W000829": "Tony Wied is a member of the United States House of Representatives from WI.",
    "W000830": "George Whitesides is a member of the United States House of Representatives from CA.",
    "W000831": "James R. Walkinshaw is a member of the United States House of Representatives from VA.",
    "Y000064": "Todd Young is a member of the United States Senate from IN.",
    "Y000067": "Rudy Yakym III is a member of the United States House of Representatives from IN.",
    "Z000018": "Ryan K. Zinke is a member of the United States House of Representatives from MT.",
}
