"""
Auto-generated member bios — regenerate with generate_bios.py
"""

MEMBER_BIOS = {
    "A000055": "Robert B. Aderholt is a member of the United States House of Representatives from Alabama.",
    "A000148": "Jake Auchincloss is a member of the United States House of Representatives from Massachusetts.",
    "A000369": "Mark E. Amodei is a member of the United States House of Representatives from Nevada.",
    "A000370": "Alma S. Adams is a member of the United States House of Representatives from North Carolina.",
    "A000371": "Pete Aguilar is a member of the United States House of Representatives from California.",
    "A000372": "Rick W. Allen is a member of the United States House of Representatives from Georgia.",
    "A000375": "Jodey C. Arrington is a member of the United States House of Representatives from Texas.",
    "A000379": "Mark Alford is a member of the United States House of Representatives from Missouri.",
    "A000380": "Gabe Amo is a member of the United States House of Representatives from Rhode Island.",
    "A000381": "Yassamin Ansari is a member of the United States House of Representatives from Arizona.",
    "A000382": "Angela D. Alsobrooks is a member of the United States Senate from Maryland.",
    "A000383": "Alan Armstrong is a member of the United States Senate from Oklahoma.",
    "B000490": "Sanford D. Bishop, Jr. is a member of the United States House of Representatives from Georgia.",
    "B000668": "Cliff Bentz is a member of the United States House of Representatives from Oregon.",
    "B000740": "Stephanie I. Bice is a member of the United States House of Representatives from Oklahoma.",
    "B000825": "Lauren Boebert is a member of the United States House of Representatives from Colorado.",
    "B001230": "Tammy Baldwin is a member of the United States Senate from Wisconsin.",
    "B001236": "John Boozman is a member of the United States Senate from Arkansas.",
    "B001243": "Marsha Blackburn is a member of the United States Senate from Tennessee.",
    "B001257": "Gus M. Bilirakis is a member of the United States House of Representatives from Florida.",
    "B001260": "Vern Buchanan is a member of the United States House of Representatives from Florida.",
    "B001261": "John Barrasso is a member of the United States Senate from Wyoming.",
    "B001267": "Michael F. Bennet is a member of the United States Senate from Colorado.",
    "B001277": "Richard Blumenthal is a member of the United States Senate from Connecticut.",
    "B001278": "Suzanne Bonamici is a member of the United States House of Representatives from Oregon.",
    "B001281": "Joyce Beatty is a member of the United States House of Representatives from Ohio.",
    "B001282": "Andy Barr is a member of the United States House of Representatives from Kentucky.",
    "B001285": "Julia Brownley is a member of the United States House of Representatives from California.",
    "B001287": "Ami Bera is a member of the United States House of Representatives from California.",
    "B001288": "Cory A. Booker is a member of the United States Senate from New Jersey.",
    "B001291": "Brian Babin is a member of the United States House of Representatives from Texas.",
    "B001292": "Donald S. Beyer, Jr. is a member of the United States House of Representatives from Virginia.",
    "B001295": "Mike Bost is a member of the United States House of Representatives from Illinois.",
    "B001296": "Brendan F. Boyle is a member of the United States House of Representatives from Pennsylvania.",
    "B001298": "Don Bacon is a member of the United States House of Representatives from Nebraska.",
    "B001299": "Jim Banks is a member of the United States Senate from Indiana.",
    "B001300": "Nanette Diaz Barragán is a member of the United States House of Representatives from California.",
    "B001301": "Jack Bergman is a member of the United States House of Representatives from Michigan.",
    "B001302": "Andy Biggs is a member of the United States House of Representatives from Arizona.",
    "B001303": "Lisa Blunt Rochester is a member of the United States Senate from Delaware.",
    "B001305": "Ted Budd is a member of the United States Senate from North Carolina.",
    "B001306": "Troy Balderson is a member of the United States House of Representatives from Ohio.",
    "B001307": "James R. Baird is a member of the United States House of Representatives from Indiana.",
    "B001309": "Tim Burchett is a member of the United States House of Representatives from Tennessee.",
    "B001313": "Shontel M. Brown is a member of the United States House of Representatives from Ohio.",
    "B001314": "Aaron Bean is a member of the United States House of Representatives from Florida.",
    "B001315": "Nikki Budzinski is a member of the United States House of Representatives from Illinois.",
    "B001316": "Eric Burlison is a member of the United States House of Representatives from Missouri.",
    "B001317": "Josh Brecheen is a member of the United States House of Representatives from Oklahoma.",
    "B001318": "Becca Balint is a member of the United States House of Representatives from Vermont.",
    "B001319": "Katie Boyd Britt is a member of the United States Senate from Alabama.",
    "B001321": "Tom Barrett is a member of the United States House of Representatives from Michigan.",
    "B001322": "Michael Baumgartner is a member of the United States House of Representatives from Washington.",
    "B001323": "Nicholas J. Begich III is a member of the United States House of Representatives from Alaska.",
    "B001324": "Wesley Bell is a member of the United States House of Representatives from Missouri.",
    "B001325": "Sheri Biggs is a member of the United States House of Representatives from South Carolina.",
    "B001326": "Janelle S. Bynum is a member of the United States House of Representatives from Oregon.",
    "B001327": "Robert P. Bresnahan, Jr. is a member of the United States House of Representatives from Pennsylvania.",
    "C000059": "Ken Calvert is a member of the United States House of Representatives from California.",
    "C000127": "Maria Cantwell is a member of the United States Senate from Washington.",
    "C000537": "Jim Clyburn is a member of the United States House of Representatives from South Carolina.",
    "C000880": "Mike Crapo is a member of the United States Senate from Idaho.",
    "C001035": "Susan M. Collins is a member of the United States Senate from Maine.",
    "C001039": "Kat Cammack is a member of the United States House of Representatives from Florida.",
    "C001047": "Shelley Moore Capito is a member of the United States Senate from West Virginia.",
    "C001051": "John R. Carter is a member of the United States House of Representatives from Texas.",
    "C001053": "Tom Cole is a member of the United States House of Representatives from Oklahoma.",
    "C001055": "Ed Case is a member of the United States House of Representatives from Hawaii.",
    "C001056": "John Cornyn is a member of the United States Senate from Texas.",
    "C001059": "Jim Costa is a member of the United States House of Representatives from California.",
    "C001061": "Emanuel Cleaver is a member of the United States House of Representatives from Missouri.",
    "C001063": "Henry Cuellar is a member of the United States House of Representatives from Texas.",
    "C001066": "Kathy Castor is a member of the United States House of Representatives from Florida.",
    "C001067": "Yvette D. Clarke is a member of the United States House of Representatives from New York.",
    "C001068": "Steve Cohen is a member of the United States House of Representatives from Tennessee.",
    "C001069": "Joe Courtney is a member of the United States House of Representatives from Connecticut.",
    "C001072": "André Carson is a member of the United States House of Representatives from Indiana.",
    "C001075": "Bill Cassidy is a member of the United States Senate from Louisiana.",
    "C001080": "Judy Chu is a member of the United States House of Representatives from California.",
    "C001087": "Rick Crawford is a member of the United States House of Representatives from Arkansas.",
    "C001088": "Christopher A. Coons is a member of the United States Senate from Delaware.",
    "C001091": "Joaquin Castro is a member of the United States House of Representatives from Texas.",
    "C001095": "Tom Cotton is a member of the United States Senate from Arkansas.",
    "C001096": "Kevin Cramer is a member of the United States Senate from North Dakota.",
    "C001098": "Ted Cruz is a member of the United States Senate from Texas.",
    "C001101": "Katherine M. Clark is a member of the United States House of Representatives from Massachusetts.",
    "C001103": "Buddy Carter is a member of the United States House of Representatives from Georgia.",
    "C001108": "James Comer is a member of the United States House of Representatives from Kentucky.",
    "C001110": "J. Luis Correa is a member of the United States House of Representatives from California.",
    "C001112": "Salud O. Carbajal is a member of the United States House of Representatives from California.",
    "C001113": "Catherine Cortez Masto is a member of the United States Senate from Nevada.",
    "C001114": "John R. Curtis is a member of the United States Senate from Utah.",
    "C001115": "Michael Cloud is a member of the United States House of Representatives from Texas.",
    "C001116": "Andrew S. Clyde is a member of the United States House of Representatives from Georgia.",
    "C001117": "Sean Casten is a member of the United States House of Representatives from Illinois.",
    "C001118": "Ben Cline is a member of the United States House of Representatives from Virginia.",
    "C001119": "Angie Craig is a member of the United States House of Representatives from Minnesota.",
    "C001120": "Dan Crenshaw is a member of the United States House of Representatives from Texas.",
    "C001121": "Jason Crow is a member of the United States House of Representatives from Colorado.",
    "C001123": "Gilbert Ray Cisneros, Jr. is a member of the United States House of Representatives from California.",
    "C001125": "Troy A. Carter is a member of the United States House of Representatives from Louisiana.",
    "C001126": "Mike Carey is a member of the United States House of Representatives from Ohio.",
    "C001129": "Mike Collins is a member of the United States House of Representatives from Georgia.",
    "C001130": "Jasmine Crockett is a member of the United States House of Representatives from Texas.",
    "C001131": "Greg Casar is a member of the United States House of Representatives from Texas.",
    "C001132": "Elijah Crane is a member of the United States House of Representatives from Arizona.",
    "C001133": "Juan Ciscomani is a member of the United States House of Representatives from Arizona.",
    "C001136": "Herbert C. Conaway, Jr. is a member of the United States House of Representatives from New Jersey.",
    "C001137": "Jeff Crank is a member of the United States House of Representatives from Colorado.",
    "D000032": "Byron Donalds is a member of the United States House of Representatives from Florida.",
    "D000096": "Danny K. Davis is a member of the United States House of Representatives from Illinois.",
    "D000197": "Diana DeGette is a member of the United States House of Representatives from Colorado.",
    "D000216": "Rosa L. DeLauro is a member of the United States House of Representatives from Connecticut.",
    "D000230": "Donald G. Davis is a member of the United States House of Representatives from North Carolina.",
    "D000399": "Lloyd Doggett is a member of the United States House of Representatives from Texas.",
    "D000530": "Christopher R. Deluzio is a member of the United States House of Representatives from Pennsylvania.",
    "D000563": "Richard J. Durbin is a member of the United States Senate from Illinois.",
    "D000594": "Monica De La Cruz is a member of the United States House of Representatives from Texas.",
    "D000600": "Mario Diaz-Balart is a member of the United States House of Representatives from Florida.",
    "D000616": "Scott DesJarlais is a member of the United States House of Representatives from Tennessee.",
    "D000617": "Suzan K. DelBene is a member of the United States House of Representatives from Washington.",
    "D000618": "Steve Daines is a member of the United States Senate from Montana.",
    "D000622": "Tammy Duckworth is a member of the United States Senate from Illinois.",
    "D000623": "Mark DeSaulnier is a member of the United States House of Representatives from California.",
    "D000624": "Debbie Dingell is a member of the United States House of Representatives from Michigan.",
    "D000626": "Warren Davidson is a member of the United States House of Representatives from Ohio.",
    "D000628": "Neal P. Dunn is a member of the United States House of Representatives from Florida.",
    "D000629": "Sharice Davids is a member of the United States House of Representatives from Kansas.",
    "D000631": "Madeleine Dean is a member of the United States House of Representatives from Pennsylvania.",
    "D000634": "Troy Downing is a member of the United States House of Representatives from Montana.",
    "D000635": "Maxine Dexter is a member of the United States House of Representatives from Oregon.",
    "E000071": "Jake Ellzey is a member of the United States House of Representatives from Texas.",
    "E000235": "Mike Ezell is a member of the United States House of Representatives from Mississippi.",
    "E000246": "Chuck Edwards is a member of the United States House of Representatives from North Carolina.",
    "E000294": "Tom Emmer is a member of the United States House of Representatives from Minnesota.",
    "E000295": "Joni Ernst is a member of the United States Senate from Iowa.",
    "E000296": "Dwight Evans is a member of the United States House of Representatives from Pennsylvania.",
    "E000297": "Adriano Espaillat is a member of the United States House of Representatives from New York.",
    "E000298": "Ron Estes is a member of the United States House of Representatives from Kansas.",
    "E000299": "Veronica Escobar is a member of the United States House of Representatives from Texas.",
    "E000300": "Gabe Evans is a member of the United States House of Representatives from Colorado.",
    "E000301": "Sarah Elfreth is a member of the United States House of Representatives from Maryland.",
    "F000110": "Cleo Fields is a member of the United States House of Representatives from Louisiana.",
    "F000246": "Pat Fallon is a member of the United States House of Representatives from Texas.",
    "F000446": "Randy Feenstra is a member of the United States House of Representatives from Iowa.",
    "F000450": "Virginia Foxx is a member of the United States House of Representatives from North Carolina.",
    "F000454": "Bill Foster is a member of the United States House of Representatives from Illinois.",
    "F000459": "Chuck Fleischmann is a member of the United States House of Representatives from Tennessee.",
    "F000462": "Lois Frankel is a member of the United States House of Representatives from Florida.",
    "F000463": "Deb Fischer is a member of the United States Senate from Nebraska.",
    "F000466": "Brian K. Fitzpatrick is a member of the United States House of Representatives from Pennsylvania.",
    "F000468": "Lizzie Fletcher is a member of the United States House of Representatives from Texas.",
    "F000469": "Russ Fulcher is a member of the United States House of Representatives from Idaho.",
    "F000470": "Michelle Fischbach is a member of the United States House of Representatives from Minnesota.",
    "F000471": "Scott Fitzgerald is a member of the United States House of Representatives from Wisconsin.",
    "F000472": "Scott Franklin is a member of the United States House of Representatives from Florida.",
    "F000474": "Mike Flood is a member of the United States House of Representatives from Nebraska.",
    "F000475": "Brad Finstad is a member of the United States House of Representatives from Minnesota.",
    "F000476": "Maxwell Frost is a member of the United States House of Representatives from Florida.",
    "F000477": "Valerie P. Foushee is a member of the United States House of Representatives from North Carolina.",
    "F000478": "Russell Fry is a member of the United States House of Representatives from South Carolina.",
    "F000479": "John Fetterman is a member of the United States Senate from Pennsylvania.",
    "F000480": "Vince Fong is a member of the United States House of Representatives from California.",
    "F000481": "Shomari Figures is a member of the United States House of Representatives from Alabama.",
    "F000482": "Julie Fedorchak is a member of the United States House of Representatives from North Dakota.",
    "F000483": "Laura Friedman is a member of the United States House of Representatives from California.",
    "F000484": "Randy Fine is a member of the United States House of Representatives from Florida.",
    "F000485": "Clay Fuller is a member of the United States House of Representatives from Georgia.",
    "G000359": "Lindsey Graham is a member of the United States Senate from South Carolina.",
    "G000386": "Chuck Grassley is a member of the United States Senate from Iowa.",
    "G000546": "Sam Graves is a member of the United States House of Representatives from Missouri.",
    "G000553": "Al Green is a member of the United States House of Representatives from Texas.",
    "G000555": "Kirsten E. Gillibrand is a member of the United States Senate from New York.",
    "G000558": "Brett Guthrie is a member of the United States House of Representatives from Kentucky.",
    "G000559": "John Garamendi is a member of the United States House of Representatives from California.",
    "G000565": "Paul A. Gosar is a member of the United States House of Representatives from Arizona.",
    "G000568": "H. Morgan Griffith is a member of the United States House of Representatives from Virginia.",
    "G000574": "Ruben Gallego is a member of the United States Senate from Arizona.",
    "G000576": "Glenn Grothman is a member of the United States House of Representatives from Wisconsin.",
    "G000581": "Vicente Gonzalez is a member of the United States House of Representatives from Texas.",
    "G000583": "Josh Gottheimer is a member of the United States House of Representatives from New Jersey.",
    "G000585": "Jimmy Gomez is a member of the United States House of Representatives from California.",
    "G000586": "Chuy García is a member of the United States House of Representatives from Illinois.",
    "G000587": "Sylvia R. Garcia is a member of the United States House of Representatives from Texas.",
    "G000589": "Lance Gooden is a member of the United States House of Representatives from Texas.",
    "G000591": "Michael Guest is a member of the United States House of Representatives from Mississippi.",
    "G000592": "Jared F. Golden is a member of the United States House of Representatives from Maine.",
    "G000593": "Carlos A. Gimenez is a member of the United States House of Representatives from Florida.",
    "G000597": "Andrew R. Garbarino is a member of the United States House of Representatives from New York.",
    "G000598": "Robert Garcia is a member of the United States House of Representatives from California.",
    "G000599": "Daniel S. Goldman is a member of the United States House of Representatives from New York.",
    "G000600": "Marie Gluesenkamp Perez is a member of the United States House of Representatives from Washington.",
    "G000601": "Craig A. Goldman is a member of the United States House of Representatives from Texas.",
    "G000602": "Laura Gillen is a member of the United States House of Representatives from New York.",
    "G000603": "Brandon Gill is a member of the United States House of Representatives from Texas.",
    "G000604": "Maggie Goodlander is a member of the United States House of Representatives from New Hampshire.",
    "G000605": "Adam Gray is a member of the United States House of Representatives from California.",
    "G000606": "Adelita S. Grijalva is a member of the United States House of Representatives from Arizona.",
    "H000273": "John W. Hickenlooper is a member of the United States Senate from Colorado.",
    "H000601": "Bill Hagerty is a member of the United States Senate from Tennessee.",
    "H000874": "Steny H. Hoyer is a member of the United States House of Representatives from Maryland.",
    "H001042": "Mazie K. Hirono is a member of the United States Senate from Hawaii.",
    "H001046": "Martin Heinrich is a member of the United States Senate from New Mexico.",
    "H001047": "Jim Himes is a member of the United States House of Representatives from Connecticut.",
    "H001052": "Andy Harris is a member of the United States House of Representatives from Maryland.",
    "H001058": "Bill Huizenga is a member of the United States House of Representatives from Michigan.",
    "H001061": "John Hoeven is a member of the United States Senate from North Dakota.",
    "H001066": "Steven Horsford is a member of the United States House of Representatives from Nevada.",
    "H001067": "Richard Hudson is a member of the United States House of Representatives from North Carolina.",
    "H001068": "Jared Huffman is a member of the United States House of Representatives from California.",
    "H001072": "J. French Hill is a member of the United States House of Representatives from Arkansas.",
    "H001076": "Maggie Hassan is a member of the United States Senate from New Hampshire.",
    "H001077": "Clay Higgins is a member of the United States House of Representatives from Louisiana.",
    "H001079": "Cindy Hyde-Smith is a member of the United States Senate from Mississippi.",
    "H001081": "Jahana Hayes is a member of the United States House of Representatives from Connecticut.",
    "H001082": "Kevin Hern is a member of the United States House of Representatives from Oklahoma.",
    "H001085": "Chrissy Houlahan is a member of the United States House of Representatives from Pennsylvania.",
    "H001086": "Diana Harshbarger is a member of the United States House of Representatives from Tennessee.",
    "H001089": "Josh Hawley is a member of the United States Senate from Missouri.",
    "H001090": "Josh Harder is a member of the United States House of Representatives from California.",
    "H001091": "Ashley Hinson is a member of the United States House of Representatives from Iowa.",
    "H001093": "Erin Houchin is a member of the United States House of Representatives from Indiana.",
    "H001094": "Val T. Hoyle is a member of the United States House of Representatives from Oregon.",
    "H001095": "Wesley Hunt is a member of the United States House of Representatives from Texas.",
    "H001096": "Harriet M. Hageman is a member of the United States House of Representatives from Wyoming.",
    "H001098": "Abraham J. Hamadeh is a member of the United States House of Representatives from Arizona.",
    "H001099": "Mike Haridopolos is a member of the United States House of Representatives from Florida.",
    "H001100": "Jeff Hurd is a member of the United States House of Representatives from Colorado.",
    "H001101": "Pat Harrigan is a member of the United States House of Representatives from North Carolina.",
    "H001102": "Mark Harris is a member of the United States House of Representatives from North Carolina.",
    "H001103": "Pablo José Hernández is a member of the United States House of Representatives from Puerto Rico.",
    "H001104": "Jon Husted is a member of the United States Senate from Ohio.",
    "I000056": "Darrell Issa is a member of the United States House of Representatives from California.",
    "I000058": "Glenn Ivey is a member of the United States House of Representatives from Maryland.",
    "J000288": "Hank Jr. is a member of the United States House of Representatives from Georgia.",
    "J000289": "Jim Jordan is a member of the United States House of Representatives from Ohio.",
    "J000293": "Ron Johnson is a member of the United States Senate from Wisconsin.",
    "J000294": "Hakeem S. Jeffries is a member of the United States House of Representatives from New York.",
    "J000295": "David P. Joyce is a member of the United States House of Representatives from Ohio.",
    "J000298": "Pramila Jayapal is a member of the United States House of Representatives from Washington.",
    "J000299": "Mike Johnson is a member of the United States House of Representatives from Louisiana.",
    "J000301": "Dusty Johnson is a member of the United States House of Representatives from South Dakota.",
    "J000302": "John Joyce is a member of the United States House of Representatives from Pennsylvania.",
    "J000304": "Ronny Jackson is a member of the United States House of Representatives from Texas.",
    "J000305": "Sara Jacobs is a member of the United States House of Representatives from California.",
    "J000307": "John James is a member of the United States House of Representatives from Michigan.",
    "J000309": "Jonathan L. Jackson is a member of the United States House of Representatives from Illinois.",
    "J000310": "Julie Johnson is a member of the United States House of Representatives from Texas.",
    "J000311": "Brian Jack is a member of the United States House of Representatives from Georgia.",
    "J000312": "James C. Justice is a member of the United States Senate from West Virginia.",
    "K000009": "Marcy Kaptur is a member of the United States House of Representatives from Ohio.",
    "K000367": "Amy Klobuchar is a member of the United States Senate from Minnesota.",
    "K000375": "William R. Keating is a member of the United States House of Representatives from Massachusetts.",
    "K000376": "Mike Kelly is a member of the United States House of Representatives from Pennsylvania.",
    "K000377": "Mark Kelly is a member of the United States Senate from Arizona.",
    "K000383": "Angus S. King, Jr. is a member of the United States Senate from Maine.",
    "K000384": "Tim Kaine is a member of the United States Senate from Virginia.",
    "K000385": "Robin L. Kelly is a member of the United States House of Representatives from Illinois.",
    "K000388": "Trent Kelly is a member of the United States House of Representatives from Mississippi.",
    "K000389": "Ro Khanna is a member of the United States House of Representatives from California.",
    "K000391": "Raja Krishnamoorthi is a member of the United States House of Representatives from Illinois.",
    "K000392": "David Kustoff is a member of the United States House of Representatives from Tennessee.",
    "K000393": "John Kennedy is a member of the United States Senate from Louisiana.",
    "K000394": "Andy Kim is a member of the United States Senate from New Jersey.",
    "K000397": "Young Kim is a member of the United States House of Representatives from California.",
    "K000398": "Thomas H. Kean, Jr. is a member of the United States House of Representatives from New Jersey.",
    "K000399": "Jennifer A. Kiggans is a member of the United States House of Representatives from Virginia.",
    "K000400": "Sydney Kamlager-Dove is a member of the United States House of Representatives from California.",
    "K000401": "Kevin Kiley is a member of the United States House of Representatives from California.",
    "K000402": "Timothy M. Kennedy is a member of the United States House of Representatives from New York.",
    "K000403": "Mike Kennedy is a member of the United States House of Representatives from Utah.",
    "K000404": "Kimberlyn King-Hinds is a member of the United States House of Representatives from Northern Mariana Islands.",
    "K000405": "Brad Knott is a member of the United States House of Representatives from North Carolina.",
    "L000273": "Teresa Leger Fernandez is a member of the United States House of Representatives from New Mexico.",
    "L000397": "Zoe Lofgren is a member of the United States House of Representatives from California.",
    "L000491": "Frank D. Lucas is a member of the United States House of Representatives from Oklahoma.",
    "L000557": "John B. Larson is a member of the United States House of Representatives from Connecticut.",
    "L000560": "Rick Larsen is a member of the United States House of Representatives from Washington.",
    "L000562": "Stephen F. Lynch is a member of the United States House of Representatives from Massachusetts.",
    "L000566": "Robert E. Latta is a member of the United States House of Representatives from Ohio.",
    "L000570": "Ben Ray Luján is a member of the United States Senate from New Mexico.",
    "L000571": "Cynthia M. Lummis is a member of the United States Senate from Wyoming.",
    "L000575": "James Lankford is a member of the United States Senate from Oklahoma.",
    "L000577": "Mike Lee is a member of the United States Senate from Utah.",
    "L000582": "Ted Lieu is a member of the United States House of Representatives from California.",
    "L000583": "Barry Loudermilk is a member of the United States House of Representatives from Georgia.",
    "L000585": "Darin LaHood is a member of the United States House of Representatives from Illinois.",
    "L000590": "Susie Lee is a member of the United States House of Representatives from Nevada.",
    "L000593": "Mike Levin is a member of the United States House of Representatives from California.",
    "L000595": "Julia Letlow is a member of the United States House of Representatives from Louisiana.",
    "L000596": "Anna Paulina Luna is a member of the United States House of Representatives from Florida.",
    "L000597": "Laurel M. Lee is a member of the United States House of Representatives from Florida.",
    "L000598": "Nick LaLota is a member of the United States House of Representatives from New York.",
    "L000599": "Michael Lawler is a member of the United States House of Representatives from New York.",
    "L000600": "Nicholas A. Langworthy is a member of the United States House of Representatives from New York.",
    "L000601": "Greg Landsman is a member of the United States House of Representatives from Ohio.",
    "L000602": "Summer L. Lee is a member of the United States House of Representatives from Pennsylvania.",
    "L000603": "Morgan Luttrell is a member of the United States House of Representatives from Texas.",
    "L000606": "George Latimer is a member of the United States House of Representatives from New York.",
    "L000607": "Sam T. Liccardo is a member of the United States House of Representatives from California.",
    "M000133": "Ed Markey is a member of the United States Senate from Massachusetts.",
    "M000194": "Nancy Mace is a member of the United States House of Representatives from South Carolina.",
    "M000312": "Jim McGovern is a member of the United States House of Representatives from Massachusetts.",
    "M000317": "Nicole Malliotakis is a member of the United States House of Representatives from New York.",
    "M000355": "Mitch McConnell is a member of the United States Senate from Kentucky.",
    "M000687": "Kweisi Mfume is a member of the United States House of Representatives from Maryland.",
    "M000871": "Tracey Mann is a member of the United States House of Representatives from Kansas.",
    "M000934": "Jerry Moran is a member of the United States Senate from Kansas.",
    "M001111": "Patty Murray is a member of the United States Senate from Washington.",
    "M001136": "Lisa C. McClain is a member of the United States House of Representatives from Michigan.",
    "M001137": "Gregory W. Meeks is a member of the United States House of Representatives from New York.",
    "M001143": "Betty McCollum is a member of the United States House of Representatives from Minnesota.",
    "M001153": "Lisa Murkowski is a member of the United States Senate from Alaska.",
    "M001157": "Michael T. McCaul is a member of the United States House of Representatives from Texas.",
    "M001160": "Gwen Moore is a member of the United States House of Representatives from Wisconsin.",
    "M001163": "Doris O. Matsui is a member of the United States House of Representatives from California.",
    "M001169": "Christopher Murphy is a member of the United States Senate from Connecticut.",
    "M001176": "Jeff Merkley is a member of the United States Senate from Oregon.",
    "M001177": "Tom McClintock is a member of the United States House of Representatives from California.",
    "M001184": "Thomas Massie is a member of the United States House of Representatives from Kentucky.",
    "M001188": "Grace Meng is a member of the United States House of Representatives from New York.",
    "M001194": "John R. Moolenaar is a member of the United States House of Representatives from Michigan.",
    "M001196": "Seth Moulton is a member of the United States House of Representatives from Massachusetts.",
    "M001198": "Roger Marshall is a member of the United States Senate from Kansas.",
    "M001199": "Brian J. Mast is a member of the United States House of Representatives from Florida.",
    "M001204": "Daniel Meuser is a member of the United States House of Representatives from Pennsylvania.",
    "M001205": "Carol D. Miller is a member of the United States House of Representatives from West Virginia.",
    "M001206": "Joseph D. Morelle is a member of the United States House of Representatives from New York.",
    "M001208": "Lucy McBath is a member of the United States House of Representatives from Georgia.",
    "M001210": "Gregory F. Murphy is a member of the United States House of Representatives from North Carolina.",
    "M001211": "Mary E. Miller is a member of the United States House of Representatives from Illinois.",
    "M001212": "Barry Moore is a member of the United States House of Representatives from Alabama.",
    "M001213": "Blake D. Moore is a member of the United States House of Representatives from Utah.",
    "M001214": "Frank J. Mrvan is a member of the United States House of Representatives from Indiana.",
    "M001215": "Mariannette Miller-Meeks is a member of the United States House of Representatives from Iowa.",
    "M001216": "Cory Mills is a member of the United States House of Representatives from Florida.",
    "M001217": "Jared Moskowitz is a member of the United States House of Representatives from Florida.",
    "M001218": "Richard McCormick is a member of the United States House of Representatives from Georgia.",
    "M001219": "James C. Moylan is a member of the United States House of Representatives from Guam.",
    "M001220": "Morgan McGarvey is a member of the United States House of Representatives from Kentucky.",
    "M001222": "Max L. Miller is a member of the United States House of Representatives from Ohio.",
    "M001223": "Seth Magaziner is a member of the United States House of Representatives from Rhode Island.",
    "M001224": "Nathaniel Moran is a member of the United States House of Representatives from Texas.",
    "M001225": "Kevin Mullin is a member of the United States House of Representatives from California.",
    "M001226": "Robert Menendez is a member of the United States House of Representatives from New Jersey.",
    "M001227": "Jennifer L. McClellan is a member of the United States House of Representatives from Virginia.",
    "M001228": "Celeste Maloy is a member of the United States House of Representatives from Utah.",
    "M001229": "LaMonica McIver is a member of the United States House of Representatives from New Jersey.",
    "M001230": "Ryan Mackenzie is a member of the United States House of Representatives from Pennsylvania.",
    "M001231": "John W. Mannion is a member of the United States House of Representatives from New York.",
    "M001232": "April McClain Delaney is a member of the United States House of Representatives from Maryland.",
    "M001233": "Mark B. Messmer is a member of the United States House of Representatives from Indiana.",
    "M001234": "Kelly Morrison is a member of the United States House of Representatives from Minnesota.",
    "M001235": "Riley M. Moore is a member of the United States House of Representatives from West Virginia.",
    "M001236": "Tim Moore is a member of the United States House of Representatives from North Carolina.",
    "M001237": "Kristen McDonald Rivet is a member of the United States House of Representatives from Michigan.",
    "M001238": "Sarah McBride is a member of the United States House of Representatives from Delaware.",
    "M001239": "John J. McGuire III is a member of the United States House of Representatives from Virginia.",
    "M001240": "Addison P. McDowell is a member of the United States House of Representatives from North Carolina.",
    "M001241": "Dave Min is a member of the United States House of Representatives from California.",
    "M001242": "Bernie Moreno is a member of the United States Senate from Ohio.",
    "M001243": "David McCormick is a member of the United States Senate from Pennsylvania.",
    "M001244": "Ashley Moody is a member of the United States Senate from Florida.",
    "M001245": "Christian D. Menefee is a member of the United States House of Representatives from Texas.",
    "N000002": "Jerrold Nadler is a member of the United States House of Representatives from New York.",
    "N000015": "Richard E. Neal is a member of the United States House of Representatives from Massachusetts.",
    "N000026": "Troy E. Nehls is a member of the United States House of Representatives from Texas.",
    "N000147": "Eleanor Holmes Norton is a member of the United States House of Representatives from District of Columbia.",
    "N000188": "Donald Norcross is a member of the United States House of Representatives from New Jersey.",
    "N000189": "Dan Newhouse is a member of the United States House of Representatives from Washington.",
    "N000190": "Ralph Norman is a member of the United States House of Representatives from South Carolina.",
    "N000191": "Joe Neguse is a member of the United States House of Representatives from Colorado.",
    "N000193": "Zachary Nunn is a member of the United States House of Representatives from Iowa.",
    "O000019": "Jay Obernolte is a member of the United States House of Representatives from California.",
    "O000086": "Burgess Owens is a member of the United States House of Representatives from Utah.",
    "O000172": "Alexandria Ocasio-Cortez is a member of the United States House of Representatives from New York.",
    "O000173": "Ilhan Omar is a member of the United States House of Representatives from Minnesota.",
    "O000174": "Jon Ossoff is a member of the United States Senate from Georgia.",
    "O000175": "Andrew Ogles is a member of the United States House of Representatives from Tennessee.",
    "O000176": "Johnny Olszewski, Jr. is a member of the United States House of Representatives from Maryland.",
    "O000177": "Robert F. Onder, Jr. is a member of the United States House of Representatives from Missouri.",
    "P000034": "Frank Pallone, Jr. is a member of the United States House of Representatives from New Jersey.",
    "P000048": "August Pfluger is a member of the United States House of Representatives from Texas.",
    "P000145": "Alex Padilla is a member of the United States Senate from California.",
    "P000197": "Nancy Pelosi is a member of the United States House of Representatives from California.",
    "P000595": "Gary C. Peters is a member of the United States Senate from Michigan.",
    "P000597": "Chellie Pingree is a member of the United States House of Representatives from Maine.",
    "P000603": "Rand Paul is a member of the United States Senate from Kentucky.",
    "P000605": "Scott Perry is a member of the United States House of Representatives from Pennsylvania.",
    "P000607": "Mark Pocan is a member of the United States House of Representatives from Wisconsin.",
    "P000608": "Scott H. Peters is a member of the United States House of Representatives from California.",
    "P000609": "Gary J. Palmer is a member of the United States House of Representatives from Alabama.",
    "P000610": "Stacey E. Plaskett is a member of the United States House of Representatives from U.S. Virgin Islands.",
    "P000613": "Jimmy Panetta is a member of the United States House of Representatives from California.",
    "P000614": "Chris Pappas is a member of the United States House of Representatives from New Hampshire.",
    "P000617": "Ayanna Pressley is a member of the United States House of Representatives from Massachusetts.",
    "P000620": "Brittany Pettersen is a member of the United States House of Representatives from Colorado.",
    "P000621": "Nellie Pou is a member of the United States House of Representatives from New Jersey.",
    "P000622": "Jimmy Patronis is a member of the United States House of Representatives from Florida.",
    "Q000023": "Mike Quigley is a member of the United States House of Representatives from Illinois.",
    "R000122": "Jack Reed is a member of the United States Senate from Rhode Island.",
    "R000305": "Deborah K. Ross is a member of the United States House of Representatives from North Carolina.",
    "R000395": "Hal Rogers is a member of the United States House of Representatives from Kentucky.",
    "R000575": "Mike Rogers is a member of the United States House of Representatives from Alabama.",
    "R000579": "Patrick Ryan is a member of the United States House of Representatives from New York.",
    "R000584": "James E. Risch is a member of the United States Senate from Idaho.",
    "R000599": "Raul Ruiz is a member of the United States House of Representatives from California.",
    "R000600": "Aumua Amata Coleman Radewagen is a member of the United States House of Representatives from American Samoa.",
    "R000603": "David Rouzer is a member of the United States House of Representatives from North Carolina.",
    "R000605": "Mike Rounds is a member of the United States Senate from South Dakota.",
    "R000606": "Jamie Raskin is a member of the United States House of Representatives from Maryland.",
    "R000608": "Jacky Rosen is a member of the United States Senate from Nevada.",
    "R000609": "John H. Rutherford is a member of the United States House of Representatives from Florida.",
    "R000610": "Guy Reschenthaler is a member of the United States House of Representatives from Pennsylvania.",
    "R000612": "John W. Rose is a member of the United States House of Representatives from Tennessee.",
    "R000614": "Chip Roy is a member of the United States House of Representatives from Texas.",
    "R000617": "Delia C. Ramirez is a member of the United States House of Representatives from Illinois.",
    "R000618": "Pete Ricketts is a member of the United States Senate from Nebraska.",
    "R000619": "Michael A. Rulli is a member of the United States House of Representatives from Ohio.",
    "R000620": "Luz M. Rivas is a member of the United States House of Representatives from California.",
    "R000621": "Emily Randall is a member of the United States House of Representatives from Washington.",
    "R000622": "Josh Riley is a member of the United States House of Representatives from New York.",
    "S000033": "Bernie Sanders is a member of the United States Senate from Vermont.",
    "S000148": "Chuck Schumer is a member of the United States Senate from New York.",
    "S000168": "Maria Elvira Salazar is a member of the United States House of Representatives from Florida.",
    "S000185": "Bobby Scott is a member of the United States House of Representatives from Virginia.",
    "S000250": "Pete Sessions is a member of the United States House of Representatives from Texas.",
    "S000344": "Brad Sherman is a member of the United States House of Representatives from California.",
    "S000510": "Adam Smith is a member of the United States House of Representatives from Washington.",
    "S000522": "Chris Smith is a member of the United States House of Representatives from New Jersey.",
    "S000929": "Victoria Spartz is a member of the United States House of Representatives from Indiana.",
    "S001145": "Jan Schakowsky is a member of the United States House of Representatives from Illinois.",
    "S001148": "Mike Simpson is a member of the United States House of Representatives from Idaho.",
    "S001150": "Adam B. Schiff is a member of the United States Senate from California.",
    "S001156": "Linda T. Sánchez is a member of the United States House of Representatives from California.",
    "S001159": "Marilyn Strickland is a member of the United States House of Representatives from Washington.",
    "S001172": "Adrian Smith is a member of the United States House of Representatives from Nebraska.",
    "S001176": "Steve Scalise is a member of the United States House of Representatives from Louisiana.",
    "S001181": "Jeanne Shaheen is a member of the United States Senate from New Hampshire.",
    "S001183": "David Schweikert is a member of the United States House of Representatives from Arizona.",
    "S001184": "Tim Scott is a member of the United States Senate from South Carolina.",
    "S001185": "Terri A. Sewell is a member of the United States House of Representatives from Alabama.",
    "S001188": "Marlin A. Stutzman is a member of the United States House of Representatives from Indiana.",
    "S001189": "Austin Scott is a member of the United States House of Representatives from Georgia.",
    "S001190": "Brad Schneider is a member of the United States House of Representatives from Illinois.",
    "S001194": "Brian Schatz is a member of the United States Senate from Hawaii.",
    "S001195": "Jason Smith is a member of the United States House of Representatives from Missouri.",
    "S001196": "Elise M. Stefanik is a member of the United States House of Representatives from New York.",
    "S001198": "Dan Sullivan is a member of the United States Senate from Alaska.",
    "S001199": "Lloyd Smucker is a member of the United States House of Representatives from Pennsylvania.",
    "S001200": "Darren Soto is a member of the United States House of Representatives from Florida.",
    "S001201": "Thomas R. Suozzi is a member of the United States House of Representatives from New York.",
    "S001203": "Tina Smith is a member of the United States Senate from Minnesota.",
    "S001205": "Mary Gay Scanlon is a member of the United States House of Representatives from Pennsylvania.",
    "S001208": "Elissa Slotkin is a member of the United States Senate from Michigan.",
    "S001211": "Greg Stanton is a member of the United States House of Representatives from Arizona.",
    "S001212": "Pete Stauber is a member of the United States House of Representatives from Minnesota.",
    "S001213": "Bryan Steil is a member of the United States House of Representatives from Wisconsin.",
    "S001214": "W. Gregory Steube is a member of the United States House of Representatives from Florida.",
    "S001215": "Haley M. Stevens is a member of the United States House of Representatives from Michigan.",
    "S001216": "Kim Schrier is a member of the United States House of Representatives from Washington.",
    "S001217": "Rick Scott is a member of the United States Senate from Florida.",
    "S001218": "Melanie A. Stansbury is a member of the United States House of Representatives from New Mexico.",
    "S001220": "Dale W. Strong is a member of the United States House of Representatives from Alabama.",
    "S001221": "Hillary J. Scholten is a member of the United States House of Representatives from Michigan.",
    "S001223": "Emilia Strong Sykes is a member of the United States House of Representatives from Ohio.",
    "S001224": "Keith Self is a member of the United States House of Representatives from Texas.",
    "S001225": "Eric Sorensen is a member of the United States House of Representatives from Illinois.",
    "S001226": "Andrea Salinas is a member of the United States House of Representatives from Oregon.",
    "S001227": "Eric Schmitt is a member of the United States Senate from Missouri.",
    "S001228": "Derek Schmidt is a member of the United States House of Representatives from Kansas.",
    "S001229": "Jefferson Shreve is a member of the United States House of Representatives from Indiana.",
    "S001230": "Suhas Subramanyam is a member of the United States House of Representatives from Virginia.",
    "S001231": "Lateefah Simon is a member of the United States House of Representatives from California.",
    "S001232": "Tim Sheehy is a member of the United States Senate from Montana.",
    "T000165": "Thomas P. Tiffany is a member of the United States House of Representatives from Wisconsin.",
    "T000193": "Bennie G. Thompson is a member of the United States House of Representatives from Mississippi.",
    "T000250": "John Thune is a member of the United States Senate from South Dakota.",
    "T000278": "Tommy Tuberville is a member of the United States Senate from Alabama.",
    "T000460": "Mike Thompson is a member of the United States House of Representatives from California.",
    "T000463": "Michael R. Turner is a member of the United States House of Representatives from Ohio.",
    "T000467": "Glenn Thompson is a member of the United States House of Representatives from Pennsylvania.",
    "T000468": "Dina Titus is a member of the United States House of Representatives from Nevada.",
    "T000469": "Paul Tonko is a member of the United States House of Representatives from New York.",
    "T000472": "Mark Takano is a member of the United States House of Representatives from California.",
    "T000474": "Norma J. Torres is a member of the United States House of Representatives from California.",
    "T000476": "Thom Tillis is a member of the United States Senate from North Carolina.",
    "T000478": "Claudia Tenney is a member of the United States House of Representatives from New York.",
    "T000480": "William R. Timmons IV is a member of the United States House of Representatives from South Carolina.",
    "T000481": "Rashida Tlaib is a member of the United States House of Representatives from Michigan.",
    "T000482": "Lori Trahan is a member of the United States House of Representatives from Massachusetts.",
    "T000486": "Ritchie Torres is a member of the United States House of Representatives from New York.",
    "T000487": "Jill N. Tokuda is a member of the United States House of Representatives from Hawaii.",
    "T000488": "Shri Thanedar is a member of the United States House of Representatives from Michigan.",
    "T000490": "David J. Taylor is a member of the United States House of Representatives from Ohio.",
    "T000491": "Derek Tran is a member of the United States House of Representatives from California.",
    "U000040": "Lauren Underwood is a member of the United States House of Representatives from Illinois.",
    "V000081": "Nydia M. Velázquez is a member of the United States House of Representatives from New York.",
    "V000128": "Chris Van Hollen is a member of the United States Senate from Maryland.",
    "V000129": "David G. Valadao is a member of the United States House of Representatives from California.",
    "V000130": "Juan Vargas is a member of the United States House of Representatives from California.",
    "V000131": "Marc A. Veasey is a member of the United States House of Representatives from Texas.",
    "V000133": "Jefferson Van Drew is a member of the United States House of Representatives from New Jersey.",
    "V000134": "Beth Van Duyne is a member of the United States House of Representatives from Texas.",
    "V000135": "Derrick Van Orden is a member of the United States House of Representatives from Wisconsin.",
    "V000136": "Gabe Vasquez is a member of the United States House of Representatives from New Mexico.",
    "V000138": "Eugene Simon Vindman is a member of the United States House of Representatives from Virginia.",
    "V000139": "Matt Van Epps is a member of the United States House of Representatives from Tennessee.",
    "W000187": "Maxine Waters is a member of the United States House of Representatives from California.",
    "W000437": "Roger F. Wicker is a member of the United States Senate from Mississippi.",
    "W000779": "Ron Wyden is a member of the United States Senate from Oregon.",
    "W000788": "Nikema Williams is a member of the United States House of Representatives from Georgia.",
    "W000790": "Raphael G. Warnock is a member of the United States Senate from Georgia.",
    "W000795": "Joe Wilson is a member of the United States House of Representatives from South Carolina.",
    "W000797": "Debbie Wasserman Schultz is a member of the United States House of Representatives from Florida.",
    "W000798": "Tim Walberg is a member of the United States House of Representatives from Michigan.",
    "W000800": "Peter Welch is a member of the United States Senate from Vermont.",
    "W000802": "Sheldon Whitehouse is a member of the United States Senate from Rhode Island.",
    "W000804": "Robert J. Wittman is a member of the United States House of Representatives from Virginia.",
    "W000805": "Mark R. Warner is a member of the United States Senate from Virginia.",
    "W000806": "Daniel Webster is a member of the United States House of Representatives from Florida.",
    "W000808": "Frederica S. Wilson is a member of the United States House of Representatives from Florida.",
    "W000809": "Steve Womack is a member of the United States House of Representatives from Arkansas.",
    "W000812": "Ann Wagner is a member of the United States House of Representatives from Missouri.",
    "W000814": "Randy K. Weber, Sr. is a member of the United States House of Representatives from Texas.",
    "W000816": "Roger Williams is a member of the United States House of Representatives from Texas.",
    "W000817": "Elizabeth Warren is a member of the United States Senate from Massachusetts.",
    "W000821": "Bruce Westerman is a member of the United States House of Representatives from Arkansas.",
    "W000822": "Bonnie Watson Coleman is a member of the United States House of Representatives from New Jersey.",
    "W000829": "Tony Wied is a member of the United States House of Representatives from Wisconsin.",
    "W000830": "George Whitesides is a member of the United States House of Representatives from California.",
    "W000831": "James R. Walkinshaw is a member of the United States House of Representatives from Virginia.",
    "Y000064": "Todd Young is a member of the United States Senate from Indiana.",
    "Y000067": "Rudy Yakym III is a member of the United States House of Representatives from Indiana.",
    "Z000018": "Ryan K. Zinke is a member of the United States House of Representatives from Montana.",
}
